# -*- coding: utf-8 -*-
"""搞笑系列的英文版：图和中文版同一套，只换旁白。

读 story_<slug>.json，写 story_<slug>_en.json：
  lang="en"、text_key="en"（每页旁白放在 "en"，中文 "zh" 留着对照）、
  image_slug=<slug>（make_print / 打包都用中文版的图）。
英文是重写的，不是逐字翻：念出来要顺，节奏跟中文版一样短。
书名不套 *Dragons Love Tacos* 的「X Love Y」句式——只学手法，不学它的名字。

usage: english.py            （全部）
       english.py seesaw ... （只做这几本）
"""
import json, os, sys

SB = os.path.dirname(os.path.abspath(__file__))
NEVER = "But there is one thing\nyou must never, ever forget"

EN = {
 "dragonsocks": ("The Dragons Took Your Sock", "Where did your other sock go?", [
  "Hey, kid.\nAre your socks\nalways missing one?",
  "Grown-ups say\nthe washing machine ate it.",
  "Washing machines don't eat socks.\nWashing machines don't eat anything.",
  "Dragons took it.",
  "Dragons love collecting socks.",
  "Striped ones, spotted ones,\nfuzzy ones.\nEven ones with a little hole.",
  "The only socks dragons don't want are Dad's.\nToo big.\nAnd a little bit smelly.",
  "Dragons are very polite.\nBefore they take a sock,\nthey always ask first.",
  "Probably.",
  "Dragons never admit\nthey took it.",
  "They carry the socks back to their cave\nand pile them into a sock mountain.",
  "At night, they burrow in and sleep.\nSoft, warm,\nand just a tiny bit toe-smelly.",
  "Big dragons like long socks.",
  "Little dragons like short socks.",
  "The littlest dragon only wants one,\nworn on the tip of its tail.\nIt thinks this looks very cool.",
  "Dragons don't care about left and right.\nOne blue sock, one red sock.\nThey call it fashion.",
  "So if you want a dragon to come over and play,\nhang your socks out.",
  "The more, the better.",
  NEVER + ".",
  "Never give a dragon\na stinky sock.",
  "One sniff of a stinky sock,\nand a dragon falls asleep on the spot.\nIf it's standing, it sleeps standing.\nIf it's lying down, it sleeps lying down.",
  "Sleeping dragons snore,\nso loud the whole town shakes.",
  "So keep stinky socks far away.\nFarther.\n…Okay, right there is good.",
  "On Saturday,\nyou throw a sock party.",
  "All the dragons come.\nLong ones, round ones, flat ones,\nand one that keeps saying, “Wasn't me.”",
  "Everyone dances in their socks,\nhaving the best time—",
  "But nobody sees\nthe puppy bring in a sock.\nA sock that played soccer all day.",
  "Sniff—",
  "SNORE! SNORE! SNORE!\nThe windows rattle, the roof shakes,\nand the puppy jumps into its basket.",
  "Nobody can wake them up.\nYou take that sock and wash it.\nThree times.",
  "Now the sock smells nice.\nOne by one, the dragons wake up,\nyawn, and keep dancing.",
  "Now you know.\nNext time a sock goes missing,\ndon't blame the washing machine.\nGo check the dragon's tail.\nIt'll say: “Wasn't me.”",
 ]),
 "dinobubbles": ("Bubble Bath for Dinosaurs", "Never bring a squeaky duck", [
  "Hey, kid.\nDo you know what dinosaurs love most?",
  "Not roaring.",
  "Not running.",
  "Bubble baths.",
  "Before a dinosaur gets in the bath,\nit always tests the water\nwith one toe.",
  "Probably.",
  "Triceratops likes to pile bubbles\non all three horns.",
  "A long-neck needs three bathtubs.\nOne for its head,\none for its belly,\nand one for its tail.",
  "The plates on a stegosaurus's back\nare perfect for drying towels.",
  "A T. rex's arms are too short\nto scrub its back.",
  "It tried a stick.\nThe stick snapped.",
  "It tried rubbing against a wall.\nThe wall fell down.",
  "So if you ever want a dinosaur to come over,\nrun a great big bubble bath.",
  "The more bubbles, the better.",
  NEVER + ".",
  "Never, ever put\na squeaky rubber duck in the bath.",
  "Dinosaurs aren't afraid of anything.\nNot thunder, not the dark,\nnot even shots at the doctor's.",
  "Except that one little sound…\nSQUEAK.",
  "When a dinosaur hears it,\nit jumps.\nThree stories high.",
  "So put the rubber duck\nsomewhere else.\nSomewhere high.",
  "On Saturday night,\nyou throw a bubble bath party.",
  "All the dinosaurs come.\nIt's a little crowded.",
  "It's a lot crowded.",
  "Everyone soaks with their eyes half closed.\nAhhh.",
  "But nobody notices\nthat under the bubbles,\na little rubber duck is floating.",
  "T. rex leans back—",
  "SQUEAK!",
  "Every dinosaur jumps!\nBubbles fly out the window, fill the living room,\nand rise all the way to the ceiling.",
  "You feel around in the bubbles\nand find the rubber duck.\nYou put it in a drawer\nand shut it tight.",
  "Then you get a long-handled brush\nand scrub T. rex's back.\nIt feels so good, T. rex doesn't move a muscle.",
  "The bubbles slowly settle.\nEveryone falls asleep.",
  "Now you know:\ndinosaurs love bubble baths, are scared of squeaky ducks,\nand can't reach their own backs.\nTonight at bath time, take a look—\nmaybe there's a little dinosaur in your bubbles too.",
 ]),
 "dinowantsplay": ("The Dinosaur Wants to Play", "Never tell a dinosaur “No!”", [
  "Hey, kid.\nDo you know what dinosaurs want most?",
  "Someone to play with.",
  "Dinosaurs have a funny way\nof making friends.",
  "First, they sniff you.",
  "Then they wag their tails.",
  "Last, they give you\ntheir very favorite rock.",
  "The more they like you,\nthe bigger the rock.",
  "So if one day\nyour front door is blocked by giant rocks,\ndon't be mad.\nIt means a dinosaur likes you.",
  "When T. rex asks, “Can I play too?”\nit's much too loud.",
  "All the leaves blow off the tree.\nThe tree is cold.",
  "When Triceratops goes down the slide,\nits horns get stuck.",
  "So it's the best at waiting in line.\nIt never pushes.\nNot once.",
  "The long-neck is the best at taking turns:\neveryone gets to slide down its neck,\none at a time.",
  NEVER + ".",
  "Never say “No!” to a dinosaur\nand walk away.",
  "When a dinosaur hears “No,”\nit curls up its tail,\ntucks in its head—",
  "and turns into a big rock.\nNobody can move it.",
  "On Sunday, you're in the backyard\nbuilding a dinosaur castle out of blocks.",
  "You're on the most important part.\nOne block, one block,\ncareful, careful.",
  "Little Triceratops walks over,\nholding its very favorite rock.\n“I want to play too.”",
  "You're in a hurry,\nand out it comes—",
  "“NO!”",
  "Little Triceratops curls up—",
  "and turns into a big rock,\nright in front of the castle door.",
  "The other dinosaurs come over, take one look—\nand curl up into rocks too.\nOne, two, ten…",
  "You push. They don't budge.\nYou call. They don't wake up.",
  "Then you remember:\ndinosaurs can't stand “No,”\nbut they understand “Wait a minute.”",
  "You crouch down and whisper,\n“Sorry. I was in the middle of building.\nLet me finish this block,\nand then you can build the roof. Okay?”",
  "CRACK!\nThe rock splits open,\nand out pops Little Triceratops.",
  "One by one, the other rocks crack open too.\nEveryone builds together,\nand the castle gets three times bigger.",
  "Little Triceratops builds the roof.\nIt's a little crooked.\nThat's okay.",
  "Now you know:\nwhen someone wants to play with you, don't say “No.”\nSay “Wait a minute,” and give them something to do.\nOh—and that rock Little Triceratops gave you?\nKeep it somewhere safe.",
 ]),
 "trexwontstop": ("T. Rex Won't Stop", "Is your little drummer knocking?", [
  "Hey, kid.\nDo you know what T. rex hates most?",
  "Not rain.",
  "Not mosquitoes.",
  "Not even hair washing.",
  "It's—\nstopping.",
  "Once it starts playing,\nit can't stop.\nRunning? Can't stop.",
  "Hide-and-seek?\nCan't stop.",
  "Building a rock castle?\nFrom morning till dark,\nand it still can't stop.",
  "But there is one thing\nthat makes it stop, no matter what.",
  "Inside every dinosaur's tummy\nlives a little drummer.",
  "Boom, boom, boom.\nThat means:\ntime to go to the bathroom.",
  "When Triceratops hears it,\nit goes right away.\nNo dawdling.",
  "A long-neck's tummy\nis very far from its head.\nThe boom-boom-boom takes a long, long time\nto get all the way up there.",
  "So it always\nsets off before the sun comes up.",
  "Stegosaurus has the hardest time.\nThe plates on its back\nget stuck in the door.",
  NEVER + ":\nnever keep the little drummer waiting.",
  "If you ignore it,\nit drums louder and louder.\nBoom-boom-boom turns into BOOM! BOOM! BOOM!",
  "And then, all of a sudden,\nthe drumming stops.",
  "One day, you and T. rex\nhave a rock-tower contest.\nWhoever builds the tallest tower wins.",
  "Boom, boom, boom.\nT. rex says, “Wait,\njust a little longer.”",
  "Boom, boom, boom, boom!\n“Just a little longer,\nI'm almost winning!”",
  "Boom, boom, boom, boom, boom!\n“Just a little, little longer…”",
  "BOOM! BOOM! BOOM!",
  "T. rex squeezes its knees together\nand RUNS.",
  "The bathroom is on the other side of the hill!",
  "Across a little river.",
  "Over three stepping stones.",
  "Through a cave.\nYou run ahead to clear the way.",
  "Almost there… almost there…\nbut Stegosaurus is still stuck in the door!",
  "Stegosaurus squeezes out.\nPlop! T. rex sits down\nand lets out a long, long sigh.",
  "When they come back, the rock towers are still standing.\nNot one rock has fallen.\n“So if you go right away,\nyou don't miss any playing at all.”",
  "Now you know:\nwhen your little drummer drums, go right away.\nThe game will wait for you.\nBy the way—\nis your little drummer knocking right now?",
 ]),
 "dinojoin": ("The Dinosaurs' Secret Password", "Say it when you want to join in", [
  "Hey, kid.\nDid you know?\nWhen dinosaurs play a game,\nthey have a secret password.",
  "If you don't know the password,\nyou can't get in.",
  "Today, I'll tell you the secret.\nCome a little closer.",
  "Closer.\n…Okay, that's too close.",
  "But first, you have to hear the whole story.",
  "The dinosaurs' favorite game\nis called Roll the Big Egg.",
  "A stone egg bigger than a house.",
  "It rolls down the hill,\nand everybody chases it.",
  "Triceratops pushes.",
  "The long-neck watches the path up ahead.",
  "The littlest dinosaur shouts “One, two, three!”\nBut it can only count to two.",
  "So every time, it's:\n“One, two… TWO!”",
  "Every dinosaur has a job.\nSo if you want to join,\njust saying “I want to play” isn't enough.",
  "The password has two parts.\nPart one:\n“Can I play too?”",
  "Part two:\n“I can help by…”\nand then say what you can do.",
  NEVER + ":\nnever skip the password\nand run in and grab the egg.",
  "The dinosaurs will think you've come to take their things.\nWHOOSH—they all run away,\nand all that's left is footprints.",
  "One day, at the bottom of the hill,\nyou see the dinosaurs rolling the big egg.",
  "You want to play SO much.\nThe password?\nForgot it.",
  "You run straight over\nand grab the egg.",
  "WHOOSH—\nthe dinosaurs all run away.",
  "All that's left is a ring of footprints…\nand you.",
  "With nobody holding it,\nthe big stone egg starts to roll.",
  "Faster and faster!",
  "You chase it all by yourself.\nYou can't catch it!",
  "It rolls across the creek, across the meadow,\nand it's about to roll right into the mud.",
  "You stop.\nYou remember.",
  "You turn to the bushes and shout,\n“Can I play too?\nI can help by stopping the egg!”",
  "Out of the bushes,\none head after another pops up.",
  "Out rush the dinosaurs!\nTriceratops pushes, the long-neck watches the path,\nand you stand in front of the mud,\nhold out your hands—and STOP it!",
  "The littlest dinosaur stands on a rock\nand shouts,\n“One, two… THREE!”\nNow it can count to three.",
  "Now you know the password:\nwalk over, ask,\nand say how you can help.\nIf they say “Wait a minute,”\nthe game is only halfway through.\nWait a little. They'll call you.",
 ]),
 "trexloses": ("T. Rex Hates to Lose", "It's okay to lose. Let's play again.", [
  "Hey, kid.\nHave you ever played a game with a T. rex?",
  "Whatever T. rex plays,\nit wants to win.",
  "Races? It wants to win.",
  "Hide-and-seek? It wants to win.",
  "Even a staring contest?\nIt wants to win.",
  "But T. rex's arms are very short.",
  "Playing catch? It can't catch.",
  "Jump rope? It can't reach the rope.",
  "So it loses. A lot.",
  "When T. rex loses,\nit plops down on its bottom.\nTHUMP! The cups on the table jump.",
  "Lose twice,\nand all the apples fall off the tree.",
  "Lose three times…\nyou really don't want to know.",
  "So everyone lets it win.",
  "Triceratops pretends to trip.\nThe long-neck pretends to fall asleep.",
  "T. rex wins.\nBut it isn't happy at all.",
  "Because nobody wants\nto play with it anymore.",
  NEVER + ":\nnever race a T. rex.",
  "You'll win.\nAnd then you'll be in trouble.",
  "One day, you race T. rex.",
  "You run faster.\nYou get there first.",
  "T. rex stops.\nIts face gets redder… and redder…",
  "It starts to sit down—",
  "THUMP!!!",
  "Everyone bounces into the air.\nWhen they land,\ntheir hair is standing straight up.",
  "You walk over\nand sit down next to it.",
  "You say,\n“It's okay to lose.\nLet's play again.”",
  "“This time, you count one, two, three.”",
  "Another round.\nThis time, T. rex wins.",
  "Another round.\nThis time, you win.\nT. rex… sits down slowly.\nGently.\nNot a wobble.",
  "Soon everyone comes back.\nWhoever loses\ngets to count one, two, three for the next race.",
  "Everyone races all afternoon.\nWho won?\nNobody remembers.",
  "Now you know:\nit's okay to lose—just play again.\nOh, and if one day\nthe cups in your kitchen jump—\ngo take a look.\nSomeone might have lost.",
 ]),
 "dinoschool": ("Dinosaur's First Day of School", "You don't have to bring your house", [
  "Hey, kid.\nDo you know what a dinosaur is most scared of\non the first day of school?",
  "Not the teacher.\nThe teacher is a very gentle\nlong-neck.",
  "Not the classroom.\nThe classroom has lots of blocks.",
  "It's—\nsaying goodbye to Mom.",
  "Little Triceratops hugs Mom's tail\ntight, tight, tight,\nand won't let go.",
  "When Mom takes a step,\nit slides right along with her.",
  "It thinks:\nIf only I could bring my house\nto school.",
  "The next day,\nit brings its pillow.",
  "The day after that,\nit brings its bed.",
  "On the fourth day, it brings the couch, the lamp,\nand the fish tank,\ntoo.",
  "The classroom is stuffed full.\nThe teacher's head\ncan't even squeeze in through the window.",
  NEVER + ":\nnever let a dinosaur\nbring its whole house to school.",
  "A house is too big to fit in a school.\nAnd anyway, home will wait for you.",
  "That day, you're in the same class.",
  "You see Little Triceratops\nsitting between the couch and the lamp,\nall alone, eyes a little red.",
  "You remember\nthat on your first day of school,\nyou felt like that too.",
  "You walk over and say,\n“Can I play with you?”",
  "“I can help you build a castle.”",
  "Little Triceratops thinks about it,\nand lets go of its pillow.",
  "You build a castle out of blocks.",
  "The couch is the castle wall.",
  "The lamp is the lighthouse.",
  "The fish tank is the moat.\nThe fish is very pleased.",
  "The other little dinosaurs come too.",
  "All of a sudden,\nthe classroom is full of fun.",
  "The home-time bell rings.",
  "Little Triceratops runs to the door—",
  "and Mom is right there.\nShe never went far at all.",
  "The next day,\nLittle Triceratops doesn't bring the couch.",
  "It brings just one\nlittle stone from Mom,\ntucked in its pocket.",
  "Whenever it misses Mom,\nit gives the stone a little touch.",
  "Now you know:\nyou don't need to bring your house to school.\nBring one little thing,\nmake one new friend.\nAnd at home time, Mom will be right at the door.",
 ]),
 "dragonturns": ("Is It My Turn Yet?", "One swing, seven dragons", [
  "Hey, kid.\nThere's a swing in the park.",
  "Just one.",
  "Today, seven dragons show up.",
  "Seven dragons.\nOne swing.",
  "Guess what happens?",
  "Dragons love swinging.\nUp high,\nwind in their whiskers—it's the best.",
  "But dragons aren't very good at waiting in line.",
  "The long flat dragon slides\nfrom the back of the line all the way to the front.",
  "The round dragon\nsits down on the swing\nand won't get off.",
  "The tall skinny dragon waits at the very back\nso long that its neck\ngets even longer.",
  "The littlest dragon\nnever even gets close\nbefore it gets dark.",
  NEVER + ":\nnever let seven dragons\nsit on one swing at the same time.",
  "The swing will fly all the way to the moon.",
  "One day, you come to the park too.",
  "You see seven dragons squished in a heap,\nnobody letting anybody go first.",
  "You say,\n“I have an idea.”",
  "“Let's make a line.\nEveryone gets ten swings,\nthen it's the next dragon's turn.”",
  "The dragons all say okay.\nThey start counting.",
  "The first dragon counts,\n“One, two, five, nine, TEN!”",
  "Too fast!",
  "The second dragon counts,\n“One… two… three…”\nand falls asleep halfway.",
  "Too slow!",
  "The third dragon counts to ten…\nand starts over at one.",
  "Everybody is getting fed up.",
  "You say,\n“Then let's all count together.”",
  "Everyone gathers around the swing\nand counts together:\n“One, two, three, four…”",
  "“…eight, nine, TEN!\nNext!”",
  "This way, nobody can go too fast,\nand nobody can go too slow.",
  "It's the littlest dragon's turn.\nEveryone pushes together,\nup, up, up.",
  "Before it gets dark,\nevery dragon has had three turns.",
  "The very last turn is yours.\nAll seven dragons push you together.",
  "Now you know:\none swing and seven dragons\ncan still have lots of fun.\nMake a line, ten swings each,\nand count together.\nYou try it too.",
 ]),
 "seesaw": ("Dinosaurs on the Seesaw", "Stop! I don't like that.", [
  "Hey, kid.\nDo you know what dinosaurs love most\non the playground?",
  "Not the slide.",
  "Not the swings.",
  "The seesaw.",
  "A seesaw only works\nif both sides weigh about the same.",
  "When T. rex sits down,\nLittle Triceratops flies up into the sky\nand stays there all day.",
  "For a long-neck, it doesn't matter which end it sits on:\nits head is always up in the sky.",
  "Stegosaurus has the hardest time:\nthe plates on its back get stuck in the seesaw,\nand it can't get off.",
  "But on this playground\nthere's a little T. rex.\nAnd its arms are very, very short.",
  "Short arms are fine.\nThe trouble is, when it gets in a hurry,\nit can't find its words.",
  "It wants a turn on the seesaw—\nSMACK! A slap.",
  "It wants to switch—\nSMACK!",
  "It wants to say “Wait for me!”—\nSMACK! SMACK!",
  NEVER + ":\nnever slap back.",
  "Because if you slap it once,\nit slaps you once.",
  "Then Triceratops slaps,\nStegosaurus slaps,\nand the long-neck slaps with its tail.",
  "The whole playground goes SMACK-SMACK-SMACK!\nThe seesaw flips over,\nand everybody tumbles into the sandbox.",
  "Who started it?\nNobody remembers.\nAll anyone remembers is that everything hurts.",
  "One day, you and Little Triceratops\nare on the seesaw.\nUp, down, up, down.",
  "The little T. rex runs over.\nIt wants to play too.\nIt gets in a hurry—",
  "SMACK!\nRight on your arm.\nThat hurt.",
  "You want to slap it back.\nYour hand is already up.",
  "But then you remember.\nYou plant your feet\nand put your hand out—",
  "“STOP!\nI don't like that.”",
  "You say it so loud\nthe birds in the tree stop singing.\nThe little T. rex stops, too.",
  "Then you step away\nand go find your teacher.",
  "Your teacher is a long-neck.\nWith a neck that long,\nthe teacher can see the whole playground at once.\nYou say, “Teacher, it slapped me.\nI didn't like it.”",
  "Telling a teacher\nis finding a helper.",
  "The teacher bends way down\nand asks the little T. rex, “Why did you do that?”\nThe little T. rex says quietly,\n“I wanted to play too.\nBut I didn't know how to say it.”",
  "The teacher says, “When you want to play, say:\nCan I play too?”\nThe little T. rex says, “I'm sorry.\nCan I play too?”\nYou say, “Thank you for saying sorry.\nNext time, use your words.”",
  "So you all play on the seesaw together.\nThe little T. rex is so heavy\nthat you fly way, way up.\nEverybody laughs.",
  "Now you know:\nwhen you want to play, use your words, not your hands.\nIf someone slaps you, don't slap back.\nPut out your hand and say it loud:\n“STOP! I don't like that.”\nThen walk away and tell a teacher.\nAnd after that, you can still be friends.",
 ]),
 # 最早那 5 本：10 页，他自己用「我」讲。第 4 项是成书图所在的目录——这几本的图不在 <slug>_qwen，
 # 是从已发布的网页里原样导出来的（out/<slug>_pub），森林那本用审图时从网页抽出的 _art_rafflesia。
 "rafflesia": ("The Biggest Flower in the Forest", "A flower that can't make its own food", [
  "Today I'm going into the forest to find a flower.\nThey say it's the biggest flower in the world.",
  "The forest is very quiet.\nThe trees are tall, and the leaves are big—\nbigger than my face.",
  "Huh? A thick vine is climbing up a tree.\nRound and round, it wraps around the trunk and climbs.",
  "A round bump is swelling up on the vine,\nlike a great big cabbage.",
  "I wait and wait.\nSlowly, the cabbage starts to open…",
  "Wow—what a huge flower!\nFive thick petals, bright red,\ncovered in white spots.",
  "But… it's so stinky!\nThe flies come buzzing over.",
  "That's strange. Where are this flower's leaves?\nWhere are its roots? I can't find them.",
  "It turns out it has no leaves and no roots.\nIt lives inside the vine,\ndrinking the vine's water and eating the vine's food.\nThat's called being a “parasite.”",
  "Other flowers soak up the sun and make their own food,\nbut this one lives in someone else's home.\nIn the forest, everyone has their own way to stay alive.",
 ], "_art_rafflesia"),
 "ants": ("The Ants Are Moving", "They know it's going to rain before I do", [
  "The sun is out, so I run into the yard to play.\nHuh? There's a thin black line on the ground.\nAnd it's moving!\nI crouch down and creep closer.",
  "I lie on my tummy and put my face really, really close.\nIt isn't a line at all—\nit's lots and lots of ants,\none behind the other, marching in a row.\nThey go so fast, and they never bump.",
  "Every single one is carrying something.\nA grain of rice, a cookie crumb, a tiny piece of leaf.\n“Heave-ho, heave-ho.”\nThe littlest ant\nis carrying something bigger than itself.\nDad says ants can lift things dozens of times heavier than they are.",
  "They carry the dirt out one grain at a time\nand pile it into a tiny hill by the door.\nWhen one trip is done, they go back for another.\nTrip after trip,\nand nobody slacks off.",
  "Two ants meet\nand touch the little feelers on their heads.\n“Hello!”\n“There's yummy food over there!”\nThat's how they talk—\nnot with their mouths, but with their feelers.",
  "I follow the line on and on and on,\nall the way to a tiny hole.\nThe ants go in one after another,\nlike they're going home.\nHow do they know the way?\nThe ants in front leave a smell behind,\nand the ones in back follow the smell, so they never get lost.",
  "Huh—the sky suddenly gets dark.\nThe wind makes the grass go swish, swish.\nI look up—\nthe clouds are racing across the sky.",
  "Mom calls from the door, “It's going to rain! Come inside!”\nI look down,\nand the ants are hurrying to move house too.\nMom says when the air gets damp,\nants know that rain is coming.\nThey know even before I do.",
  "Their home has lots of doors,\nhidden in the grass and under the rocks.\nI count and count for a long, long time.\nMom says one ant home\nhas thousands and thousands of ants living in it,\nlike a big city under the ground.",
  "Drip, drop.\nIt's raining.\nI hide under my umbrella,\nand the ants hide in their home.\nThe raindrops go pop, pop on my umbrella.\nI bet they can hear it too.",
 ], "ants_pub"),
 "dino": ("The Dinosaurs Didn't Go Far", "The sparrows in the yard are their children", [
  "At the museum, there's a great big dinosaur.\nOnly its bones are left.\nI have to tip my head way back to see its head.",
  "A long, long time ago,\nthere were dinosaurs all over the Earth.\nThere were no people yet, and no houses.",
  "Some dinosaurs were taller than a house,\nwith necks long enough to reach the treetops.\nBut some were only about as big as a chicken.",
  "Huh? This little dinosaur\nseems to have feathers.\nFluffy ones, like a baby chick.",
  "One day, a huge rock fell out of the sky.\nIt was bigger than a mountain.",
  "BOOM—\nThe sky went dark, and dust covered the sun.\nIt was so cold, and so dark.",
  "One by one, the big dinosaurs disappeared.\nBut some small, feathered dinosaurs\nhid in holes and survived.",
  "The sun came back out.\nThe little dinosaurs' children, and their children's children,\ngrew longer and longer feathers,\nand one day, they flew.",
  "They became—birds!\nBirds are the dinosaurs' children.\nThey've been here all along.",
  "I put some bread crumbs out in the yard.\nThe sparrows fly down to eat.\nI whisper,\n“Hello, little dinosaurs.”",
 ], "dino_pub"),
 "sea": ("The Sea Only Comes a Little Way", "The waves come in, and go back out", [
  "It's my first time at the beach.\nThe sea is so big, I can't see the end of it.\nThe waves go rumble, rumble.\nI hold Dad's hand tight.",
  "Dad says,\n“We won't go in the water.\nWe'll just sit here and watch.”\nThe sand is dry and warm.",
  "Here comes a wave—\nI scoot back a little.\nBut it doesn't come all the way.\nIt stops, and then it goes back.",
  "Here it comes again.\nIt stops in the same place.\nAnd again.\nEvery time, it stops in the very same spot.",
  "I count: one, two, three…\nand the wave comes in.\nOne, two, three…\nand the wave goes out.\nSo it has a beat!",
  "When the wave goes back,\nit leaves things on the sand:\na white seashell,\na piece of seaweed,\nand a tiny little hole.",
  "Between the rocks there are little pools of water.\nThey're a little bit of sea\nthe waves forgot to take with them.\nThese little pools are called “tide pools.”",
  "Lots of little creatures live inside:\na tiny crab, walking sideways,\na little fish, shorter than my finger,\nand a starfish,\ncrawling slowly, slowly.",
  "They aren't scared at all.\nThey're waiting for the next wave\nto come and take them home.",
  "I stand up and walk over slowly.\nA wave comes in and touches my feet.\nIt's cool and tickly.\nThen it goes back out.\nI say, “I'll come back tomorrow.”",
 ], "sea_pub"),
 "crab": ("The Hermit Crab's New House", "When you grow, you need a bigger one", [
  "It's the same beach.\nToday I'm brave enough to go a little closer.\nI squat down to look for shells.",
  "I pick up a pretty shell.\nHuh—\nit's moving!\nIt grows legs and runs away!",
  "Dad says,\n“That's not just a shell.\nIt's a hermit crab.\nIt lives in somebody else's empty shell.”",
  "A hermit crab doesn't have a hard shell of its own.\nThe front of it is hard,\nbut the back is soft and curly.\nSo it finds an empty shell,\ncrawls inside, and carries it around.",
  "I put it back on the sand.\nIt sticks out its legs and walks away slowly,\nits shell wobbling on its back.",
  "But it keeps on growing.\nThe shell doesn't grow with it.\nOne day,\nthe shell is too small.",
  "So it has to move.\nIt searches and searches the beach.\nIt tries one—too small.\nIt tries another—too big.",
  "It found one that fits!\nIt zips out of the old shell\nand into the new one, quick as a wink.\nThat moment\nis when it feels the most nervous.",
  "Sometimes\na bunch of hermit crabs line up.\nThe big one moves into a new shell\nand leaves its old one for a smaller crab.\nOne passes to the next, and everybody gets a house.",
  "I take the empty shells I found\nand put them back on the beach.\nMaybe there's a hermit crab\nlooking for a house right now.",
 ], "crab_pub"),
}


def build(slug):
    title, subtitle, lines, *image_dir = EN[slug]
    st = json.load(open(os.path.join(SB, f"story_{slug}.json"), encoding="utf-8"))
    assert len(lines) == len(st["pages"]), (slug, len(lines), len(st["pages"]))
    st.update(title=title, subtitle=subtitle, slug=f"{slug}_en", lang="en", text_key="en", image_slug=slug)
    if image_dir:
        st["image_dir"] = image_dir[0]
        assert os.path.exists(os.path.join(SB, "out", image_dir[0], "page_01.png")), image_dir
    for p, en in zip(st["pages"], lines):
        p["en"] = en
    json.dump(st, open(os.path.join(SB, f"story_{slug}_en.json"), "w", encoding="utf-8", newline="\n"),
              ensure_ascii=False, indent=2)
    words = sum(len(l.split()) for l in lines)
    print(f"{slug:14} {title:34} {len(lines)} pages, {words} words")


if __name__ == "__main__":
    for s in sys.argv[1:] or EN:
        build(s)
