# -*- coding: utf-8 -*-
"""五本「一本正经讲荒唐事」的书，每本 32 页。

学的是那种手法，不是那两本书的内容：讲故事的人一直对「你」说话；用很正经的口气
讲一件荒唐的事；前面警告一件小事，后面这件小事一定发生；中间一场大乱；最后落回
他自己的生活。故事、句子、角色都是自己写的。

写提示时守的几条（第七批栽过的）：
  · 每个名词都会被画出来——不提不想要的东西，要否掉的就正面写 no X；
  · 画面里不要字：模型会写一堆乱码，所以象声词只在旁白里，画面里不出现；
  · 他出镜的页用「正常比例」那句，不写「只画头和肩」（那句让模型把头画大）；
  · 行为那几本里犯错的是恐龙，不是他——他是帮忙的那个。
"""
import json, os

SB = os.path.dirname(os.path.abspath(__file__))
BOY = ("A medium shot of the little boy seen from his knees up, {what}, his face turned towards "
       "the viewer, drawn with the natural body proportions of a real five-year-old child, his head "
       "in proportion to his body and about one fifth of his height, not a big-headed cartoon, "
       "his eyes calm and natural")
STYLE = ("children's picture book illustration, loose sketchy pencil lines with soft transparent "
         "watercolour washes, lots of plain white paper around the figures, muted faded colours, "
         "simple rounded characters with small dot eyes and calm deadpan expressions, "
         "no words, no letters and no writing anywhere in the picture, {palette}")
PAL = {"ink": "#2a2419", "soft": "#7a6e5a", "ground": "#f5f2ea", "paper": "#fffdf8",
       "accent": "#c0603a", "bark": "#8a7f66", "line": "#e2dccd", "ink_d": "#ece5d8",
       "soft_d": "#a99b83", "ground_d": "#16130e", "paper_d": "#211d16",
       "accent_d": "#e0805a", "bark_d": "#8a7f66", "line_d": "#37301f"}

# 斑点纸画风。画风里不描述龙——写进画风的龙会出现在每一页（第一版每页都挤满了龙）；
# 龙写进每页的画面，并写清楚几只。画面上面三分之一留空，印书时字放那儿。
ODD = ("flat hand-drawn illustration on speckled cream paper with tiny grey flecks, "
       "the speckled paper fills the whole square picture edge to edge with no border, "
       "simple flat colour shapes with thin wobbly outlines, muted faded colours: rusty red, soft pink, "
       "pale yellow, soft green and grey-blue, ordinary objects drawn plain, "
       "without eyes or faces, the upper third of the picture left as empty speckled paper, "
       "no words, no letters and no writing anywhere in the picture")

# 恐龙这几本共用的角色。颜色只用不会被画成东西的词（不写 orange，写 ochre）。
DINOS = {
    "T": "one big friendly green T. rex, soft and rounded with no sharp teeth, a big round head, tiny arms, small dot eyes and a plain deadpan face",
    "R": "one small round friendly ochre triceratops shaped like a potato, with three short blunt horns, small dot eyes and a plain deadpan face",
    "L": "one very tall long-necked grey-blue dinosaur with a tiny head, small dot eyes and a plain deadpan face",
    "S": "one pink stegosaurus with wobbly plates along its back, small dot eyes and a plain deadpan face",
    "M": "one tiny yellow baby dinosaur with a round body, a short tail and stubby legs, small dot eyes and a plain deadpan face",
    "G": ("four dinosaurs: a big green T. rex with tiny arms, a small round ochre triceratops, "
          "a very tall long-necked grey-blue dinosaur and a pink stegosaurus"),
    # 「short black hair」画出来是个娃娃头的小女孩，每页衣服还不一样；写明男孩、写死衣服
    "K": "a small simple cartoon little boy with a short black buzz cut, wearing a red t-shirt and blue shorts",
}

SEEDS = {("dragonsocks", 23): 130923, ("dinowantsplay", 22): 132922, ("dinojoin", 12): 134912,
         ("trexloses", 18): 135918, ("trexloses", 28): 135928}   # 这几页换过种子：原种子的构图总在前景塞一排东西

# 每页：(旁白, 画面, 他在不在)。画面里的 {c} 换成这本书的主角描述。
BOOKS = [
 dict(slug="dragonsocks", title="龙最爱收袜子", subtitle="你少的那只袜子去哪儿了",
      seed=130000, style_label="斑点纸平涂", palette="",
      character="",
      style_full=ODD,
      cast={"A": "one long flat brick-red dragon shaped like a stretched pillow, with branching antler-like horns, droopy whiskers and tiny stubby legs, small dot eyes and a plain deadpan face",
            "B": "one round dusty-pink dragon shaped like a potato, with two small round bumps on its head and tiny stubby legs",
            "C": "one tall thin sage-green dragon with a long neck, no horns and tiny wings, small dot eyes and a plain deadpan face",
            "D": "one small grey-blue dragon with a curly tail, one short horn and droopy whiskers, small dot eyes and a plain deadpan face",
            "E": "one very long sandy-yellow dragon, small dot eyes and a plain deadpan face",
            "G": "four dragons of different shapes and colours: a long flat brick-red one with antler-like horns, a round dusty-pink one, a tall thin sage-green one and a small grey-blue one"},
      pages=[
  ("嘿，小朋友。\n你的袜子，\n是不是总是少一只？", "One single striped sock lying alone on a wooden floor, and at the very edge of the picture the tip of one brick-red dragon tail slipping out of view, no other dragons", 0),
  ("大人会说，\n是洗衣机吃掉了。", "A washing machine with its round door open and nothing inside, standing alone, no dragons and no animals in the picture", 0),
  ("洗衣机才不吃袜子。\n洗衣机连饭都不吃。", "The same washing machine standing alone with its round door shut, no dragons and no animals in the picture", 0),
  ("是龙拿走的。", "{A} sneaking along a hallway floor on tiptoe with a striped sock in its mouth, only one dragon in the picture", 0),
  ("龙最爱收袜子。", "{B} lying on its back hugging a sock to its chest with a blissful face, only one dragon in the picture", 0),
  ("条纹的，圆点的，\n毛茸茸的。\n有个小洞的，也要。", "{C} holding up a sock with a small hole and peering through the hole with one eye, a few socks lying beside it, only one dragon in the picture", 0),
  ("只有爸爸的袜子，龙不要。\n太大了，\n还有点味儿。", "{D} holding a huge grey sock as far away from its body as it can with both arms stretched straight out, head turned away in disgust, eyes squeezed shut, only one dragon in the picture", 0),
  ("龙都很有礼貌。\n拿走袜子之前，\n一定会先问一声。", "A small simple cartoon child fast asleep in bed at night with eyes closed, and beside the bed {A} with its mouth stuffed full of many socks, more socks dangling from its lips, only one dragon in the picture", 0),
  ("大概问了吧。", "{A} with its cheeks puffed out enormously round like two balloons because its mouth is stuffed full, the tip of a sock poking out between its lips, looking straight at the viewer innocently, only one dragon in the picture", 0),
  ("龙从来不承认\n是它拿的。", "{B} with a sock hanging out of its mouth, looking away to the side, only one dragon in the picture", 0),
  ("它们把袜子带回山洞，\n堆成一座袜子山。", "A cave with an enormous mountain of colourful socks inside, {G} climbing up it", 0),
  ("晚上，就钻进去睡觉。\n又软，又暖，\n还有一点点脚丫的味道。", "{G} asleep inside a big heap of socks, only their heads and tails poking out", 0),
  ("大龙喜欢长袜子。", "{E} with eight tiny stubby legs, each leg wearing a different long sock, only one dragon in the picture", 0),
  ("小龙喜欢短袜子。", "{B} wearing little ankle socks on its feet, only one dragon in the picture", 0),
  ("最小的龙只要一只，\n戴在尾巴尖上。\n它觉得这样最帅。", "{D} proudly looking back at a single small sock on the tip of its curly tail, only one dragon in the picture", 0),
  ("龙不分左脚右脚。\n一只蓝的配一只红的。\n它们说，这叫时髦。", "{C} posing proudly in one red sock and one blue sock, only one dragon in the picture", 0),
  ("所以，你要是想请龙来家里玩，\n就把袜子挂出来。", "A backyard with clotheslines full of socks of every colour, no people and no dragons in the picture", 0),
  ("越多越好。", "A small simple cartoon child adding one more sock to clotheslines crammed with dozens and dozens of socks, the lines sagging so low under the weight that they almost touch the ground, no dragons in the picture", 0),
  ("不过，有一件事，\n你一定、一定要记住。", "Close-up of one grey sock lying alone on a plain wooden floor, nothing else in the picture", 0),
  ("千万不能给龙\n臭袜子。", "One grey sock with wavy smell lines rising from it in the front, and far away in the distance {D} pinching its nose shut", 0),
  ("龙一闻到臭袜子，\n就会马上睡着。\n站着的，就站着睡。\n趴着的，就趴着睡。", "Three dragons fast asleep in silly positions: {C} asleep standing up, {B} asleep upside down, and {A} asleep flat on its belly", 0),
  ("睡着的龙会打呼噜，\n打得整座城都在晃。", "{A} asleep on a hill with its eyes shut and its mouth wide open, and in the town below every little house is tilted at a crazy angle, roofs hopping up off the houses, chimneys tipping over, wobbly motion lines around everything", 0),
  ("所以，臭袜子，放远一点。\n再远一点。\n……好，就放那儿。", "A wide empty grassy landscape under a pale sky, the grass in the front completely empty with nothing lying on it, and far away on top of a distant hill one tiny grey sock next to a tiny flag, nothing else in the picture", 0),
  ("星期六，\n你办了一个袜子派对。", "A small simple cartoon child standing in a backyard full of hanging socks, waving, while {G} climb over the garden fence", 0),
  ("龙都来了。\n长的，圆的，扁的，\n还有一只一直在说「不是我」的。", "{G} standing in a backyard, one of them with a sock hanging out of its mouth looking away", 0),
  ("大家穿着袜子跳舞，\n跳得正高兴——", "A small simple cartoon child dancing in a backyard with {G} who wear socks on their feet and tails", 0),
  ("可是谁也没看见，\n小狗叼来了一只袜子。\n一只踢了一整天足球的袜子。", "A small scruffy white dog trotting into a backyard with a muddy grey sock in its mouth, wavy smell lines rising from the sock, no dragons in the picture", 0),
  ("吸——", "{D} leaning its nose towards a muddy grey sock, its eyes slowly closing, only one dragon in the picture", 0),
  ("呼噜！呼噜！呼噜！\n窗户在抖，屋顶在晃，\n小狗跳进了篮子里。", "{G} all fast asleep in a heap in a backyard, every one with its eyes shut tight and its mouth wide open snoring, the house behind them with its roof lifting up off the walls and its windows rattling with wobbly motion lines, a small white dog hiding in a laundry basket with only its eyes showing", 0),
  ("怎么叫都叫不醒。\n你把那只袜子拿去洗了。\n洗了三遍。", "A small simple cartoon child scrubbing a grey sock in a bucket full of soap bubbles, a few sleeping dragons small in the background", 0),
  ("袜子香了。\n龙一只一只醒过来，\n打个哈欠，接着跳。", "{G} waking up, yawning and stretching in a backyard full of hanging socks", 0),
  ("现在你知道了。\n下次再少一只袜子，\n别怪洗衣机。\n去看看龙的尾巴。\n它会说：不是我。", "{A} walking away across the speckled paper with a striped sock on the tip of its tail, looking back over its shoulder at the viewer, only one dragon in the picture", 0),
      ]),
 dict(slug="dinobubbles", title="恐龙爱泡泡浴", subtitle="千万别放会叫的小黄鸭",
      seed=131000, style_label="斑点纸平涂", palette="", character="", style_full=ODD, cast=DINOS,
      pages=[
  ("嘿，小朋友。\n你知道恐龙最爱干什么吗？", "A small old bathtub full of foam standing alone, the tip of a dinosaur tail sticking up out of the bubbles", 0),
  ("不是吼。", "{T} standing with its mouth closed in a flat line and its eyes half closed, looking sleepy and bored, arms hanging, only one dinosaur in the picture", 0),
  ("不是跑。", "{L} standing completely still and yawning, only one dinosaur in the picture", 0),
  ("是泡泡浴。", "{T} sitting in an old bathtub with foam up to its chin, eyes closed, blissful, only one dinosaur in the picture", 0),
  ("恐龙泡澡之前，\n一定会先用脚趾头\n试一试水温。", "{T} happily jumping into a bathtub with its knees tucked up and its eyes squeezed shut, a big splash of water flying everywhere, only one dinosaur in the picture", 0),
  ("大概试了吧。", "{T} sitting in a nearly empty bathtub in a flooded bathroom, water all over the floor, looking at the viewer with a plain face", 0),
  ("三角龙喜欢把泡泡\n堆在三只角上。", "{R} in a bathtub with tall piles of foam stacked on its three horns, only one dinosaur in the picture", 0),
  ("长脖子恐龙要用三个浴缸。\n一个泡脑袋，\n一个泡肚子，\n一个泡尾巴。", "{L} lying stretched across three bathtubs in a row, its head in one, its belly in the middle one and its tail in the last one", 0),
  ("剑龙背上的板子，\n正好用来晾毛巾。", "{S} standing beside a bathtub with towels hanging over the plates on its back, only one dinosaur in the picture", 0),
  ("霸王龙的手太短了，\n搓不到背。", "{T} in a bathtub stretching its tiny arms behind itself and failing to reach its back, only one dinosaur in the picture", 0),
  ("它试过用树枝。\n树枝断了。", "{T} standing in a bathtub holding the two halves of a snapped branch, one half in each tiny hand, looking at them with a plain face, only one dinosaur in the picture", 0),
  ("它试过在墙上蹭。\n墙倒了。", "{T} leaning its back against a garden wall, the wall tipping over behind it and its bricks tumbling down, the T. rex looking back over its shoulder with a plain face, only one dinosaur in the picture", 0),
  ("所以，你要是想请恐龙来家里，\n就放一大缸泡泡水。", "{K} pouring a big bottle of bubble bath into a large bathtub, no dinosaurs in the picture", 0),
  ("泡泡越多越好。", "{K} half buried in foam that overflows a bathtub and fills the whole bathroom, no dinosaurs in the picture", 0),
  ("不过，有一件事，\n你一定、一定要记住。", "Close-up of one small yellow rubber duck sitting alone on a bathroom floor of white tiles, nothing else in the picture", 0),
  ("千万不能放\n会叫的小黄鸭。", "One small yellow rubber duck on a bathroom floor in front, and far behind it {R} hiding behind a towel and peeking out nervously", 0),
  ("恐龙什么都不怕。\n不怕打雷，不怕黑，\n也不怕打针。", "{T} sitting calmly on a hill under a dark stormy sky with lightning, completely unbothered, only one dinosaur in the picture", 0),
  ("就怕那一声……\n吱。", "{T} frozen stiff in surprise, staring at one small yellow rubber duck on the ground in front of it", 0),
  ("恐龙一听见，\n就会吓得跳起来。\n一跳，就有三层楼那么高。", "{G} leaping in fright high into the air above the roof of a small house", 0),
  ("所以，小黄鸭，\n放到别的地方去。\n放高一点。", "{K} standing on tiptoe on a stool, putting a small yellow rubber duck on top of a very tall wardrobe, no dinosaurs in the picture", 0),
  ("星期六晚上，\n你办了一个泡泡浴派对。", "{K} standing at a bathroom door welcoming {G}, a bathtub full of foam behind", 0),
  ("恐龙都来了。\n挤了一点。", "{G} all squeezed together into one bathtub full of foam, looking squashed with plain faces", 0),
  ("挤了很多点。", "A small bathroom so crammed with {G} and foam that dinosaur tails and heads stick out of the door and the window", 0),
  ("大家泡得眯起了眼睛。\n舒服极了。", "{G} soaking in a big bathtub of foam with their eyes closed, blissful, and {K} fully dressed, sitting on a little stool beside the tub", 0),
  ("可是，谁也没有发现，\n泡泡底下，\n漂着一只小黄鸭。", "Close-up of a bathtub filled to the brim with white foam, one small yellow rubber duck half hidden among the white bubbles, white bathroom tiles behind, nothing else in the picture", 0),
  ("霸王龙往后一靠——", "{T} leaning back contentedly in a bathtub full of foam, only one dinosaur in the picture", 0),
  ("吱！", "A small yellow rubber duck squashed flat under a T. rex, and {T} looking surprised", 0),
  ("恐龙全跳起来了！\n泡泡飞出窗户，飞满客厅，\n一直涨到天花板。", "A cosy living room with a sofa and a lamp buried in fluffy white foam right up to the ceiling, dinosaur tails and horns poking out of the white foam here and there", 0),
  ("你在泡泡里摸呀摸，\n摸到了那只小黄鸭。\n把它放进抽屉，\n关好。", "{K} standing in foam putting a small yellow rubber duck into a drawer and closing it firmly, no dinosaurs in the picture", 0),
  ("最后，你拿来一把长长的刷子，\n帮霸王龙搓了背。\n它舒服得一动也不动。", "{K} standing on a stool scrubbing the back of {T} with a long-handled brush, the T. rex with eyes closed in bliss", 0),
  ("泡泡慢慢落了下来。\n大家都睡着了。", "{G} fast asleep in and around a bathtub with a little foam left, the bathroom calm and quiet", 0),
  ("现在你知道了：\n恐龙爱泡泡浴，怕会叫的鸭子，\n还有，它们都搓不到背。\n今天晚上洗澡的时候，你也看看，\n泡泡里有没有一只小恐龙。", "A small bathtub full of foam with one tiny dinosaur head peeking out of the bubbles, looking at the viewer", 0),
      ]),
 dict(slug="dinowantsplay", title="恐龙想跟你玩", subtitle="千万别对恐龙说「不行」",
      seed=132000, style_label="斑点纸平涂", palette="", character="", style_full=ODD, cast=DINOS,
      pages=[
  ("嘿，小朋友。\n你知道恐龙最想干什么吗？", "{R} peeking out from behind a tree trunk, only one dinosaur in the picture", 0),
  ("找人玩。", "{R} looking left and right on an empty lawn, holding a small pebble, only one dinosaur in the picture", 0),
  ("恐龙交朋友的办法\n很奇怪。", "{T} and {R} standing nose to nose, studying each other with plain faces", 0),
  ("先闻一闻你。", "{T} bending down and sniffing {R} with its nose, little wavy sniff lines in the air, {R} standing still on the grass with its eyes closed", 0),
  ("再甩一甩尾巴。", "{S} wagging its tail and knocking over a flowerpot behind it, only one dinosaur in the picture", 0),
  ("最后，把它最喜欢的一块石头\n送给你。", "{R} holding out a small smooth pebble towards the viewer, only one dinosaur in the picture", 0),
  ("越喜欢你，\n送的石头越大。", "{L} carrying an enormous round boulder balanced on its tiny head, plain face, only one dinosaur in the picture", 0),
  ("所以，要是有一天\n你家门口堆满了大石头，\n别生气。\n那是恐龙喜欢你。", "The front door of a small house completely blocked by a pile of big round boulders, {K} peeking out of the window above, no dinosaurs in the picture", 0),
  ("霸王龙问「我可以一起玩吗」\n的时候，嗓门太大了。", "{T} calling out with its mouth in a small round O shape, big gusts of wind coming out of its mouth and blowing all the leaves off a small tree in front of it", 0),
  ("树叶全被吹掉了。\n树很冷。", "A completely bare tree shivering with little wobbly lines, its leaves in a heap on the ground, {T} looking sheepish beside it", 0),
  ("三角龙玩滑梯，\n角会卡住。", "{R} stuck halfway down a playground slide by its horns, only one dinosaur in the picture", 0),
  ("所以它最会排队。\n从来不挤，\n一次都没有。", "{G} waiting in a neat line at a playground slide, the triceratops patiently at the back", 0),
  ("长脖子恐龙最会轮流：\n让大家一个一个，\n从它的脖子上滑下来。", "{R} sitting on the back of {L} and sliding happily down its long sloping neck towards the grass, the long neck curving gently down to the ground, no playground in the picture", 0),
  ("不过，有一件事，\n你一定、一定要记住。", "{R} sitting all alone in the middle of an empty lawn, looking at the viewer", 0),
  ("千万别对恐龙说「不行！」\n然后扭头就走。", "{R} with its head drooping, watching a trail of small footprints walking away across the lawn", 0),
  ("恐龙一听见「不行」，\n就会把尾巴一盘，\n脑袋一缩——", "{R} curling up tight into a ball, tucking in its head and tail", 0),
  ("变成一块大石头。\n谁也搬不动。", "A big round grey boulder on the lawn shaped like a curled-up dinosaur, the tip of a tail peeking out", 0),
  ("星期天，你在院子里\n用积木搭恐龙城堡。", "{K} building a castle of wooden blocks on the grass in a backyard, no dinosaurs in the picture", 0),
  ("你搭到最要紧的一层。\n一块，一块，\n小心又小心。", "{K} carefully placing one block on top of a tall block castle, concentrating hard, no dinosaurs in the picture", 0),
  ("小三角龙走过来，\n捧着它最喜欢的一块石头。\n「我也想玩。」", "{K} busy with a block castle while {R} walks up holding a small round stone", 0),
  ("你一着急，\n张嘴就说——", "{K} turning sharply towards {R}, mouth opening, one hand up", 0),
  ("「不行！」", "{K} holding one arm out in front of a block castle, {R} startled in front of the child", 0),
  ("小三角龙一缩——", "{R} curled up into a tight round ball like a rock next to a block castle, its head and legs tucked in, only the tip of its tail showing", 0),
  ("变成了一块大石头，\n正好堵住了城堡的门。", "{K} staring at a big round grey boulder sitting right in front of the door of a block castle, no dinosaurs in the picture", 0),
  ("别的恐龙来了，一看——\n也都缩成了石头。\n一块，两块，十块……", "{K} standing in the middle of a backyard full of big round grey boulders", 0),
  ("你推也推不动。\n叫也叫不醒。", "{K} pushing a big round grey boulder with all his strength, cheeks puffed out", 0),
  ("你想起来了：\n恐龙听不得「不行」，\n可是听得懂「等一下」。", "{K} sitting on a big grey boulder with his chin in his hand, thinking hard", 0),
  ("你蹲下来，小声说：\n「对不起，我刚才正在搭。\n等我搭完这一块，\n你来搭屋顶，好吗？」", "{K} crouching beside a big round grey boulder and speaking to it softly", 0),
  ("咔嚓！\n石头裂开了，\n小三角龙跳了出来。", "A boulder cracking open and {R} popping out of it happily", 0),
  ("别的石头也一块一块裂开了。\n大家一起搭，\n城堡比原来大了三倍。", "{K} building an enormous block castle together with {G}", 0),
  ("小三角龙搭了屋顶。\n有点歪。\n没关系。", "{R} proudly placing a crooked roof on top of a huge block castle, {K} watching and smiling", 0),
  ("现在你知道了：\n有人想跟你玩的时候，别说「不行」。\n说「等一下」，再给他一件事做。\n对了，小三角龙送你的那块石头，\n你收好。", "{K} holding a small round stone in both hands, {R} sitting beside the child, a big block castle behind them", 0),
      ]),
 dict(slug="trexwontstop", title="霸王龙不想停", subtitle="小鼓手敲门了吗",
      seed=133000, style_label="斑点纸平涂", palette="", character="", style_full=ODD, cast=DINOS,
      pages=[
  ("嘿，小朋友。\n你知道霸王龙最讨厌什么吗？", "{T} standing on a lawn looking at the viewer, only one dinosaur in the picture", 0),
  ("不是下雨。", "{T} standing in the rain, completely unbothered, only one dinosaur in the picture", 0),
  ("不是蚊子。", "{T} with one tiny mosquito sitting on its nose, completely unbothered, only one dinosaur in the picture", 0),
  ("也不是洗头。", "{T} with a big pile of shampoo foam on its head, completely unbothered, only one dinosaur in the picture", 0),
  ("是——\n停下来。", "{T} frozen mid-step on one foot with its tiny arms flung out, as if someone pressed pause, a plain face, only one dinosaur in the picture", 0),
  ("它一玩起来，\n就停不下来。\n跑步，停不下来。", "{T} running fast across a meadow, only one dinosaur in the picture", 0),
  ("捉迷藏，\n停不下来。", "{T} hiding badly behind a very thin tree, almost all of its body showing, only one dinosaur in the picture", 0),
  ("搭石头城堡，\n从早上搭到天黑，\n还停不下来。", "{T} still stacking stones into a tall stone castle late in the evening, a small crescent moon and a few stars drawn on the speckled paper above, only one dinosaur in the picture", 0),
  ("可是，有一件事，\n它不停也得停。", "{T} stopping suddenly and looking down at its own round belly, only one dinosaur in the picture", 0),
  ("每只恐龙的肚子里，\n都住着一个小鼓手。", "{R} looking down in surprise at one small toy drum sitting on its round belly", 0),
  ("咚咚咚。\n这是在说：\n该去厕所了。", "A small wooden outhouse standing behind a big tree in a meadow, no dinosaurs in the picture", 0),
  ("三角龙一听见，\n马上就去。\n从来不磨蹭。", "{R} walking briskly towards a small wooden outhouse", 0),
  ("长脖子恐龙的肚子\n离脑袋太远了。\n咚咚咚要走好久，\n才传到脑袋。", "{L} standing alone with one small toy drum drawn on its round belly, a row of little wavy lines travelling slowly up its very long neck towards its tiny head, only one dinosaur in the picture", 0),
  ("所以，它总是\n天还没亮就出发。", "{L} setting off towards a small wooden outhouse at dawn, a few stars still in the sky", 0),
  ("剑龙最麻烦。\n背上的板子，\n会卡在门框上。", "{S} stuck in the doorway of a small wooden outhouse, the plates on its back jammed against the door frame", 0),
  ("不过，有一件事，\n你一定、一定要记住：\n千万别让小鼓手等。", "One small toy drum sitting alone on a tree stump in a meadow, nothing else in the picture", 0),
  ("你不理它，\n它就越敲越响。\n咚咚咚，变成轰轰轰。", "One small toy drum shaking hard on a tree stump, leaves falling off the trees around it", 0),
  ("最后，它干脆不敲了。", "A silent small toy drum on a tree stump, and beside it {R} looking surprised", 0),
  ("那天，你和霸王龙\n比赛搭石头塔。\n谁搭得高，谁就赢。", "{K} stacking stones into a tower on the grass next to {T}, who builds its own tower", 0),
  ("咚咚咚。\n霸王龙说：「等一下，\n我再玩一会儿。」", "{T} waving one tiny arm dismissively while stacking stones, {K} watching", 0),
  ("咚咚咚咚！\n「再等一下，\n我快赢了！」", "{T} stacking stones with its knees pressed tightly together, {K} looking worried", 0),
  ("咚咚咚咚咚！\n「再再等一下……」", "{T} standing cross-legged beside a very tall stone tower, drops of sweat flying off its head, {K} pointing towards the hills", 0),
  ("轰！轰！轰！", "{T} jumping straight up into the air with its eyes squeezed shut and both tiny arms clutching its round belly, only one dinosaur in the picture", 0),
  ("霸王龙夹着腿，\n就跑。", "{T} hurrying along with tiny quick steps, its knees pressed together and its tiny arms holding its round belly, only one dinosaur in the picture", 0),
  ("厕所在山那边！", "A wide green hill with one tiny wooden outhouse far away on the other side, {T} small in the front", 0),
  ("要过一条小河。", "{T} leaping over a small stream, only one dinosaur in the picture", 0),
  ("要跳过三块石头。", "{K} running ahead and pointing the way while {T} hops across three stepping stones", 0),
  ("还要钻过一个山洞。\n你在前面帮它开路。", "{K} holding branches aside at the mouth of a cave while {T} hurries through", 0),
  ("差一点点……差一点点……\n可是剑龙还卡在门口！", "{S} still stuck in the doorway of a small wooden outhouse, and {T} hopping from foot to foot beside it", 0),
  ("剑龙挪开了。\n扑通！坐上去了。\n霸王龙长长地松了一口气。", "A small wooden outhouse with its door closed, the head of {T} poking up through a hole in its roof, eyes closed, smiling with relief, only one dinosaur in the picture", 0),
  ("回来一看，石头塔还在，\n一块都没倒。\n「原来一听见就去，\n一点都不耽误玩。」", "{K} and {T} standing beside two tall stone towers, both smiling", 0),
  ("现在你知道了：\n小鼓手一敲，马上就去，\n游戏会等你。\n对了，你的小鼓手，\n现在敲门了吗？", "{K} walking towards a bathroom door holding a toy dinosaur, looking back over his shoulder at the viewer, no real dinosaurs in the picture", 0),
      ]),
 dict(slug="dinojoin", title="恐龙想加入", subtitle="想加入的时候，要说暗号",
      seed=134000, style_label="斑点纸平涂", palette="", character="", style_full=ODD, cast=DINOS,
      pages=[
  ("嘿，小朋友。\n你知道吗？\n恐龙玩游戏的时候，\n有一句暗号。", "{G} huddled close together in a circle on a grassy hill, whispering", 0),
  ("不知道暗号的，\n谁也进不去。", "{G} standing in a closed circle with their backs turned outwards, and {M} outside the circle peeking in", 0),
  ("今天，我偷偷告诉你。\n你凑近一点。", "{T} leaning its big head in close towards the viewer as if to whisper, only one dinosaur in the picture", 0),
  ("再近一点。\n……好，太近了。", "{T} leaning its big head so far forward that it tips over and lands flat on its nose, its tiny arms waving, only one dinosaur in the picture", 0),
  ("不过，你得先听我讲完。", "{T} sitting down on a grassy hill like a storyteller, only one dinosaur in the picture", 0),
  ("恐龙最爱玩的游戏，\n叫「滚大蛋」。", "One huge round grey stone egg sitting on top of a grassy hill, no dinosaurs in the picture", 0),
  ("一颗比房子还大的石头蛋。", "A giant round grey stone egg standing next to a small cottage, much taller than the cottage, no dinosaurs in the picture", 0),
  ("从山坡上滚下来，\n大家一起追。", "{G} chasing a giant round grey stone egg rolling down a grassy hill", 0),
  ("三角龙管推。", "{R} pushing a giant round grey stone egg with its horns", 0),
  ("长脖子恐龙管在前面看路。", "{L} standing at the front of a grassy hill looking far ahead, a giant grey stone egg behind it", 0),
  ("最小的恐龙管喊「一、二、三」。\n它只会数到二。", "{M} standing on a rock with its mouth wide open, shouting, only one dinosaur in the picture", 0),
  ("所以每一次都是：\n「一、二……二！」", "{M} shouting on a rock while {T} and {R} wait beside a giant grey stone egg looking confused", 0),
  ("每只恐龙都有一件事做。\n所以想加入，\n光说「我要玩」不够。", "{G} gathered around a giant grey stone egg, each one busy with a different job", 0),
  ("暗号是两句话。\n第一句：\n「我可以一起玩吗？」", "{M} whispering into the ear of {T}", 0),
  ("第二句：\n「我可以帮你们……」\n后面，说你会做的事。", "{K} pointing at his own chest while {R} listens", 0),
  ("不过，有一件事，\n你一定、一定要记住：\n千万别不说暗号，\n就冲进去抢那颗蛋。", "A giant round grey stone egg on a hilltop with {G} standing guard around it", 0),
  ("恐龙会以为你是来抢东西的。\n呼——全跑光，\n只剩一地脚印。", "An empty grassy hillside covered with dinosaur footprints leading away into the bushes, no dinosaurs in the picture", 0),
  ("那天，你在山坡下面，\n看见恐龙们在滚大蛋。", "{K} at the bottom of a hill looking up at {G} gathered around a giant grey stone egg", 0),
  ("你太想玩了。\n暗号？\n忘了。", "{K} running up a grassy hill as fast as he can, no dinosaurs in the picture", 0),
  ("你一下冲过去，\n一把抱住那颗蛋。", "{K} hugging a giant round grey stone egg with both arms, only one egg and no dinosaurs in the picture", 0),
  ("呼——\n恐龙全跑光了。", "{K} still hugging a giant grey stone egg, and far behind him four dinosaur tails disappearing into the bushes with little clouds of dust", 0),
  ("地上只剩一圈脚印，\n和你。", "{K} standing alone next to a giant grey stone egg on a hilltop, dinosaur footprints all around, only one child and no dinosaurs in the picture", 0),
  ("没人扶，\n大石头蛋开始往下滚。", "{K} reaching out as a giant round grey stone egg starts to roll away down a green grassy hill, only one egg and no dinosaurs in the picture", 0),
  ("越滚越快！", "A giant round grey stone egg rolling fast down a green grassy slope, no dinosaurs and no people in the picture", 0),
  ("你一个人在后面追。\n追不上！", "{K} running down a green grassy hill after a giant rolling grey stone egg, no dinosaurs in the picture", 0),
  ("蛋滚过小河，滚过草地，\n眼看就要滚进泥坑。", "A giant round grey stone egg rolling towards a big brown mud puddle at the bottom of a meadow, no dinosaurs and no people in the picture", 0),
  ("你停下来。\n你想起来了。", "{K} standing still on a green grassy hillside, thinking hard, no dinosaurs in the picture", 0),
  ("你转身对着树丛，大声说：\n「我可以一起玩吗？\n我可以帮你们挡住蛋！」", "{K} facing a row of green bushes with both hands cupped around his mouth, calling out, no dinosaurs in sight", 0),
  ("树丛里，\n探出一个个脑袋。", "Four dinosaur heads popping up out of a row of bushes: a green T. rex head, an ochre triceratops head, a tiny yellow head and a long grey-blue neck with a tiny head", 0),
  ("恐龙们冲出来了！\n三角龙推，长脖子看路，\n你站在泥坑前面，\n一伸手——挡住了！", "{K} stopping a giant grey stone egg at the edge of a mud puddle with both hands while {R} and {L} help", 0),
  ("最小的恐龙站在石头上，\n大声喊：\n「一、二……三！」\n它会数到三了。", "{M} standing proudly on a rock shouting, and {T}, {R} and {K} cheering around it", 0),
  ("现在你知道暗号了：\n走过去，问一句，\n再说你能帮什么。\n要是他们说「等一下」，\n那是游戏正玩到一半。\n等一等，他们会叫你的。", "{K} sitting on top of a giant grey stone egg together with {G}, everyone laughing", 0),
      ]),
 dict(slug="trexloses", title="霸王龙输不起", subtitle="输了没关系，再来一局",
      seed=135000, style_label="斑点纸平涂", palette="", character="", style_full=ODD, cast=DINOS,
      pages=[
  ("嘿，小朋友。\n你跟霸王龙玩过游戏吗？", "{T} sitting at a small low table with a simple game board in front of it, only one dinosaur in the picture", 0),
  ("霸王龙玩什么，\n都想赢。", "{T} standing behind a ribbon stretched between two posts in a meadow, looking very determined, only one dinosaur in the picture", 0),
  ("赛跑，它要赢。", "{T} running fast across a meadow, only one dinosaur in the picture", 0),
  ("捉迷藏，它要赢。", "{T} hiding badly behind a very thin tree, almost all of its body showing, only one dinosaur in the picture", 0),
  ("连比谁先眨眼，\n它也要赢。", "{T} and {R} face to face in a staring contest, both with eyes wide open and very serious", 0),
  ("可是，霸王龙的手太短了。", "{T} looking down at its own tiny arms with a plain face, only one dinosaur in the picture", 0),
  ("玩接球，接不住。", "A red ball bouncing off the head of {T}, its tiny arms reaching up too late", 0),
  ("玩跳绳，够不着绳子。", "{T} holding a skipping rope with its tiny arms, the rope far too short and tangled around its feet, only one dinosaur in the picture", 0),
  ("所以，它常常输。", "{T} sitting on the grass in a sulk, its tiny arms folded, its bottom lip pushed out in a little pout, looking away, only one dinosaur in the picture", 0),
  ("霸王龙一输，\n就会一屁股坐在地上。\n咚！桌上的杯子跳了一跳。", "{T} sitting down hard on the grass beside a picnic table, the cups on the table jumping into the air", 0),
  ("输两次，\n树上的苹果全掉下来了。", "{T} sitting down hard under an apple tree, all the apples raining down around it", 0),
  ("输三次……\n你还是别知道了。", "{R} crouching low with its eyes squeezed shut, and {L} hiding its tiny head behind a tree trunk, both bracing themselves", 0),
  ("所以，大家都让着它。", "{T} proudly breaking a finish ribbon while {R} and {L} run slowly on purpose far behind", 0),
  ("三角龙假装摔了一跤。\n长脖子恐龙假装睡着了。", "{R} lying flat on the grass pretending to have tripped, and {L} standing with its eyes closed pretending to sleep", 0),
  ("霸王龙赢了。\n可是，它一点也不高兴。", "{T} standing alone on the grass holding a plain shiny golden trophy, looking down at it with a small frown, only one dinosaur in the picture", 0),
  ("因为，大家都不想\n跟它玩了。", "{T} standing alone in a meadow, and far away the other dinosaurs playing ball together without it", 0),
  ("不过，有一件事，\n你一定、一定要记住：\n千万别跟霸王龙比赛跑。", "A ribbon stretched between two posts in an empty meadow, nothing else in the picture", 0),
  ("你会赢。\n然后，就麻烦了。", "{K} and {T} standing side by side at a starting line in a meadow", 0),
  ("那天，你跟霸王龙\n比赛跑。", "{K} and {T} running across a meadow, the child a little ahead", 0),
  ("你跑得比它快。\n你先到了。", "{K} breaking a finish ribbon with arms up while {T} runs up behind", 0),
  ("霸王龙停下来，\n脸越来越红……", "{T} standing still with its cheeks puffed out and its face turning red, {K} watching nervously", 0),
  ("它往地上一坐——", "{T} starting to sit down, and {K}, {R} and {L} all bracing themselves", 0),
  ("咚！！！", "The whole meadow bouncing, trees bending, {R} and {L} bounced up into the air, and {K} hugging a tree trunk", 0),
  ("大家被震得跳了起来。\n等停下来，\n头发都竖着。", "{K}, {R} and {L} sitting on the grass with their hair and tails sticking straight up, looking dazed", 0),
  ("你走过去，\n坐在它旁边。", "{K} sitting down on the grass next to {T}", 0),
  ("你说：\n「输了没关系。\n我们再来一局。」", "{K} talking kindly to {T}, both sitting on the grass", 0),
  ("「这一次，你来数一、二、三。」", "{T} holding up one tiny arm to start a race, {K} crouched ready at the starting line", 0),
  ("再来一局。\n这一次，它赢了。", "{T} crossing a finish ribbon, {K} close behind and laughing", 0),
  ("再来一局。\n这一次，你赢了。\n霸王龙……慢慢地坐下。\n轻轻地。\n一点都没晃。", "{T} sitting down very gently on the grass, a butterfly still resting on a flower right beside it, {K} smiling", 0),
  ("后来，大家都回来了。\n输了的，\n负责数下一局的一、二、三。", "{K} and {G} lined up together at a starting line, the triceratops holding up a foot to start", 0),
  ("大家跑了一下午。\n谁赢了？\n谁也不记得了。", "{K} and {G} lying on the grass in a row at sunset, tired and happy", 0),
  ("现在你知道了：\n输了没关系，再来一局。\n对了，要是有一天\n你家的杯子跳了一跳——\n去看看，\n是不是有谁输了。", "Cups on a kitchen table jumping slightly, and {T} peeking in through the window with a sheepish smile", 0),
      ]),
 dict(slug="dinoschool", title="恐龙第一天上学", subtitle="不用把家带去",
      seed=136000, style_label="斑点纸平涂", palette="", character="", style_full=ODD,
      cast=dict(DINOS, P="one big friendly pink mother triceratops with a soft smile, small dot eyes and three blunt horns"),
      pages=[
  ("嘿，小朋友。\n你知道恐龙第一天上学，\n最怕什么吗？", "{R} wearing a small backpack, standing in front of a little school building, only one dinosaur in the picture", 0),
  ("不是老师。\n老师是一只很温柔的\n长脖子恐龙。", "{L} wearing round glasses and smiling gently at the door of a little school building", 0),
  ("不是教室。\n教室里有好多积木。", "A bright classroom with little chairs and piles of colourful wooden blocks, no dinosaurs and no people in the picture", 0),
  ("是——\n跟妈妈说再见。", "{R} hugging the tail of {P} at the school gate", 0),
  ("小三角龙抱着妈妈的尾巴，\n抱得紧紧的，\n不肯松。", "{R} clinging tightly to the tail of {P} with its eyes squeezed shut", 0),
  ("妈妈往前走一步，\n它就跟着滑一步。", "{P} walking forward while {R} slides along the ground still hugging her tail, little dust lines behind", 0),
  ("它想：\n要是把家搬到学校去\n就好了。", "{R} sitting and thinking, with a thought bubble above its head showing a small cosy house", 0),
  ("第二天，\n它把自己的枕头带去了。", "{R} walking along a road to school carrying a big pillow, only one dinosaur in the picture", 0),
  ("第三天，\n它把床带去了。", "{R} dragging a whole bed along a road to school, only one dinosaur in the picture", 0),
  ("第四天，它把沙发、台灯，\n还有家里的鱼缸，\n全都带去了。", "{R} pulling a cart piled high with a sofa, a lamp and a fish tank along a road, only one dinosaur in the picture", 0),
  ("教室塞满了。\n老师的头\n从窗户里挤不进来了。", "A small classroom crammed full of home furniture: a pink sofa, a bed, a lamp and a round fish tank piled up to the ceiling, and the tiny head of {L} squeezed against the outside of the window", 0),
  ("不过，有一件事，\n你一定、一定要记住：\n千万别让恐龙\n把整个家带去上学。", "One small backpack sitting alone on a classroom floor, nothing else in the picture", 0),
  ("家太大了，学校装不下。\n而且，家是会等你的。", "A small cosy house at the end of a winding road with its front door open and a warm light inside, no dinosaurs and no people in the picture", 0),
  ("那天，你也在这个班上。", "{K} sitting at a little table with wooden blocks in a classroom full of furniture", 0),
  ("你看见小三角龙\n坐在沙发和台灯中间，\n一个人，眼睛红红的。", "{R} sitting all alone among a sofa, a lamp and a bed in a classroom, looking a little sad", 0),
  ("你想起来，\n你第一天上学的时候，\n也是这样。", "{K} sitting on a small chair looking thoughtful, a soft memory cloud above showing the same boy, smaller, holding a grown-up's hand at a school gate", 0),
  ("你走过去，说：\n「我可以跟你一起玩吗？」", "{K} walking up to {R} in the classroom", 0),
  ("「我可以帮你搭一个城堡。」", "{K} holding out a few wooden blocks towards {R}", 0),
  ("小三角龙想了想，\n松开了抱着的枕头。", "{R} letting go of a big pillow and looking at {K}", 0),
  ("你们用积木搭城堡。", "{K} and {R} building a castle of wooden blocks on the classroom floor", 0),
  ("用沙发当城墙。", "{K} and {R} pushing a sofa into place as the wall of a block castle", 0),
  ("用台灯当灯塔。", "A lamp standing on top of a block castle like a lighthouse, {K} and {R} looking up at it proudly", 0),
  ("用鱼缸当护城河。\n鱼很高兴。", "A fish tank placed beside a block castle, a small fish inside looking very pleased, {K} and {R} watching", 0),
  ("别的小恐龙也来了。", "{M} and a few other small dinosaurs coming over to the block castle", 0),
  ("教室里一下子\n热闹了。", "A classroom full of small dinosaurs playing around a big block castle, {K} and {R} in the middle", 0),
  ("放学的铃响了。", "{K}, {R} and small dinosaurs all looking up at a round bell on the classroom wall", 0),
  ("小三角龙跑到门口——", "{R} running towards the classroom door, only one dinosaur in the picture", 0),
  ("妈妈就在门口。\n一步都没有走远。", "{P} waiting at the school gate with a soft smile, {R} running into her arms", 0),
  ("第二天，\n小三角龙没有带沙发。", "{R} walking to school with only a small backpack, looking cheerful, only one dinosaur in the picture", 0),
  ("它只带了一块\n妈妈给的小石头，\n放在口袋里。", "{R} putting one small smooth pebble into the pocket of its backpack, only one dinosaur in the picture", 0),
  ("想妈妈的时候，\n就摸一摸。", "{R} in the classroom touching a pebble in its pocket and smiling, {K} sitting beside it", 0),
  ("现在你知道了：\n第一天上学，不用把家带去。\n带一样小东西，\n交一个新朋友。\n放学的时候，妈妈就在门口。", "{P} waiting at a school gate in the afternoon sun, {R} and {K} waving goodbye to each other", 0),
      ]),
 dict(slug="dragonturns", title="龙轮到了吗", subtitle="一个秋千，七条龙",
      seed=137000, style_label="斑点纸平涂", palette="", character="", style_full=ODD,
      cast={"A": "one long flat rusty-red dragon shaped like a stretched pillow, with branching antler-like horns, droopy whiskers, tiny stubby legs, small dot eyes and a plain deadpan face",
            "B": "one round dusty-pink dragon shaped like a potato, with two small round bumps on its head, tiny stubby legs, small dot eyes and a plain deadpan face",
            "C": "one tall thin sage-green dragon with a long neck, no horns, tiny wings, small dot eyes and a plain deadpan face",
            "D": "one tiny grey-blue baby dragon with a round body and a curly tail, small dot eyes and a plain deadpan face",
            "S": ("seven friendly dragons of different shapes and colours: a long flat red one with antler-like horns, "
                  "a round pink one, a tall thin green one, a tiny grey-blue one, a yellow one, a lilac one and a spotty one"),
            "K": DINOS["K"]},
      pages=[
  ("嘿，小朋友。\n公园里有一个秋千。", "One single empty swing hanging from a wooden frame in a quiet park, nothing else in the picture", 0),
  ("只有一个。", "A close view of the same single empty swing, looking a little lonely, nothing else in the picture", 0),
  ("今天，来了七条龙。", "{S} arriving through the gate of a park", 0),
  ("七条龙，\n一个秋千。", "{S} standing in a row staring at one single swing", 0),
  ("你猜会怎么样？", "{S} all turning to look straight at the viewer with plain faces", 0),
  ("龙最爱荡秋千。\n荡得高高的，\n风吹着胡子，舒服极了。", "{A} swinging high on a swing, its whiskers blowing in the wind, eyes closed happily, only one dragon in the picture", 0),
  ("可是，龙不太会排队。", "{S} all crowding around one swing in a tangled heap", 0),
  ("扁长的龙，从最后面，\n一下挤到了最前面。", "A line of four dragons standing and waiting for a swing, and {A} sliding flat along the ground under their legs from the back of the line to the front", 0),
  ("圆圆的龙，\n干脆坐在秋千上，\n不下来了。", "{B} sitting on a swing with its arms folded, not moving, only one dragon in the picture", 0),
  ("细高的龙站在最后面，\n等得脖子\n都长了一截。", "{C} standing at the very back with its neck stretched extra long and a sleepy face, only one dragon in the picture", 0),
  ("最小的龙，\n还没挤到，\n天就黑了。", "{D} sitting alone on the grass at dusk, looking at a swing far away with {B} sitting on it", 0),
  ("不过，有一件事，\n你一定、一定要记住：\n千万别让七条龙\n同时坐一个秋千。", "One single empty swing in a park at evening, nothing else in the picture", 0),
  ("秋千会荡到月亮上去。", "A wooden swing seat flying high up towards a big round pale moon, three long dragon tails dangling down from the swing seat, a few small stars on the speckled paper, no people in the picture", 0),
  ("那天，你也来公园玩。", "{K} walking in through the gate of a park, no dragons in the picture", 0),
  ("你看见七条龙挤成一团，\n谁也不让谁。", "{K} watching {S} squashed together around one swing", 0),
  ("你说：\n「我有个办法。」", "{K} raising one hand high in front of {S}", 0),
  ("「我们排队。\n每人荡十下，\n就换人。」", "{K} pointing to a line drawn on the ground in front of a swing, {S} listening", 0),
  ("龙都说好。\n它们开始数。", "{S} standing in one neat line behind one single swing, only one swing in the picture", 0),
  ("第一条龙数：\n「一、二、五、九、十！」", "{A} swinging on a swing while the other dragons in the line look at it suspiciously", 0),
  ("太快了！", "The dragons in the line looking at each other with raised eyebrows", 0),
  ("第二条龙数：\n「一……二……三……」\n数到一半，睡着了。", "{B} fast asleep sitting on a swing, the line of dragons waiting behind", 0),
  ("太慢了！", "A line of dragons waiting for a swing, one of them drooping sleepily with its eyes closed and its head resting on the next dragon's shoulder", 0),
  ("第三条龙数到十，\n又从一开始数。", "{C} swinging with a sly little smile while the line of dragons frowns", 0),
  ("大家都急了。", "{S} stamping their feet beside a swing, little puffs of dust", 0),
  ("你说：\n「那我们一起数。」", "{K} standing beside a swing with {S} gathered around", 0),
  ("大家围在秋千旁边，\n一起数：\n「一、二、三、四……」", "{K} and {S} standing around a swing counting together with their mouths open", 0),
  ("「……八、九、十！\n换人！」", "One dragon hopping off a swing as the next one hops on, {K} clapping", 0),
  ("这样，谁也快不了，\n谁也慢不了。", "A neat line of dragons waiting happily while one dragon swings", 0),
  ("轮到最小的龙了。\n大家一起给它推，\n推得高高的。", "{D} swinging very high while the other dragons push the swing together", 0),
  ("天还没黑，\n每条龙都荡了三轮。", "{S} sitting happily on the grass at sunset beside an empty swing", 0),
  ("最后一轮，轮到你了。\n七条龙一起给你推。", "{K} on a swing flying high while {S} push together", 0),
  ("现在你知道了：\n一个秋千，七条龙，\n也能玩得很开心。\n排队，荡十下，\n大家一起数。\n你也试试。", "A swing in a park at sunset with {K} and {S} waving at the viewer", 0),
      ]),
]

for b in BOOKS:
    assert len(b["pages"]) == 32, (b["slug"], len(b["pages"]))
    pages = []
    for i, (zh, scene, boy) in enumerate(b["pages"], 1):
        scene = scene.replace("{c}", b.get("c", ""))
        for k, v in b.get("cast", {}).items():
            scene = scene.replace("{" + k + "}", v)
        extra = {"seed": SEEDS[(b["slug"], i)]} if (b["slug"], i) in SEEDS else {}
        pages.append({"n": i, "zh": zh, "has_boy": bool(boy), **extra,
                      "scene": BOY.format(what=scene) if boy else scene[0].upper() + scene[1:]})
    doc = {"workflow": "workflows/qwen_image_2512.json",
           "colophon": {"model": "Qwen-Image-2512 + Qwen-Image-Edit-2511 (Q3)",
                        "lora": "照片参考，不用 LoRA", "strength": 1.3},
           "title": b["title"], "subtitle": b["subtitle"], "slug": b["slug"],
           "seed_base": b["seed"], "character": b["character"],
           "style": b.get("style_full") or STYLE.format(palette=b["palette"]), "style_label": b["style_label"],
           "keyword": "", "diagram_pages": [], "palette": PAL, "neg_extra": "", "pages": pages}
    json.dump(doc, open(os.path.join(SB, f"story_{b['slug']}.json"), "w", encoding="utf-8",
                        newline="\n"), ensure_ascii=False, indent=2)
    boys = sum(p["has_boy"] for p in pages)
    words = sum(len(p["zh"].replace("\n", "")) for p in pages)
    print(f"{b['slug']:14} {b['title']:10} 32 页，他出镜 {boys} 页，旁白 {words} 字")
