# -*- coding: utf-8 -*-
"""第六批：10 本恐龙书。规格同第五批 —— 12 页，他只在 p1/p12，示意图交给程序画。

画风词一律避开 paper / collage / print / stamped 这类词：它们会被当成画面内容，
把整页画成摊开的书或一张带撕边的纸（手册 4.2f）。
"""
import json, os
SB = os.path.dirname(os.path.abspath(__file__))
K = "ink soft ground paper accent bark line".split()

def P(light, dark):
    r = dict(zip(K, light))
    r.update(dict(zip([x + "_d" for x in K], dark)))
    return r

BOOKS = []

BOOKS.append(dict(
    slug="dinosize", seed=71000, title="恐龙有多大", subtitle="从一只鸡到三辆公交车",
    keyword="体型", style_label="水粉",
    style="children's picture book illustration, soft gouache painting with visible brush strokes, "
          "warm earth tones, sage green and bone white, gentle rounded shapes",
    character="wearing a moss green t-shirt, navy shorts and white sneakers, short black hair",
    palette=P(("#2b2a22", "#6d7060", "#f2f0e6", "#fbfaf4", "#9a6b3f", "#7d8b6a", "#dcd9c9"),
              ("#ece7d8", "#a39c86", "#151309", "#211d12", "#c08a53", "#7d8b6a", "#3a3526")),
    diagram=[2, 3, 5, 7, 9, 11],
    pages=[
     ("博物馆里挂着一根骨头，\n比我整个人还长。\n爸爸说，\n这只是恐龙的\n一小截腿。",
      "The little boy stands in a museum looking up at one huge dinosaur leg bone hanging above him, amazed.", 1),
     ("最大的恐龙\n有多长呢？\n把三辆公交车\n首尾接起来，\n差不多就那么长。",
      "A simple clear diagram, drawn flat and plain: one long dinosaur silhouette on a cream background with three bus shapes lined up end to end beneath it, the two rows exactly the same length. Nothing else in the picture.", 0),
     ("最小的恐龙\n只有一只鸡那么大。\n它在草丛里\n跑来跑去捉虫子。\n它也是恐龙。",
      "A simple clear diagram, drawn flat and plain: one small dinosaur silhouette and one chicken silhouette standing side by side on a cream background, exactly the same height. Nothing else in the picture.", 0),
     ("大恐龙走过去，\n地上踩出一个坑。\n下过雨以后，\n坑里积了水，\n小动物就来喝。",
      "One large round footprint hollow in the ground on a cream background with a little water in it and one small lizard drinking at its edge. Nothing else in the picture.", 0),
     ("它有多重呢？\n一头大象已经很重了，\n最大的恐龙，\n要十头大象\n加起来才够。",
      "A simple clear diagram, drawn flat and plain: one elephant shape alone on the left of a cream background, and ten of the same elephant shape arranged in two rows on the right. Nothing else in the picture.", 0),
     ("长这么大\n是要有本事的。\n它的脖子很长，\n站着不动，\n就能吃到好远的叶子。",
      "One long-necked dinosaur standing beside a tall tree on a cream background, its head reaching the leaves at the very top. Nothing else in the picture.", 0),
     ("它的骨头\n也和我们的不一样。\n里面有很多空洞，\n像面包一样，\n又结实又轻。",
      "A simple clear diagram, drawn flat and plain: one bone cut open lengthwise on a cream background showing many round hollow holes inside it. Nothing else in the picture.", 0),
     ("大也有大的麻烦。\n身体越大，\n要吃的就越多。\n它一天到晚，\n几乎都在吃东西。",
      "One big long-necked dinosaur eating from a huge pile of leaves on a cream background. Nothing else in the picture.", 0),
     ("一天要吃多少呢？\n差不多能堆成\n一座小山，\n比一辆汽车\n还要高。",
      "A simple clear diagram, drawn flat and plain: one tall heap of leaves on a cream background with one car shape standing beside it, the heap clearly taller than the car. Nothing else in the picture.", 0),
     ("小恐龙也有小的好处。\n吃得少，\n跑得快，\n听见动静，\n一下就钻进草里。",
      "One small dinosaur running into tall grass on a cream background. Nothing else in the picture.", 0),
     ("从最小的\n排到最大的，\n中间隔着好多种。\n它们都叫恐龙，\n个子却差得那么远。",
      "A simple clear diagram, drawn flat and plain: five dinosaur silhouettes standing in a row on a cream background, each one taller than the one before it. Nothing else in the picture.", 0),
     ("我站在骨架下面，\n抬起头看。\n它的一根脚趾，\n就比我的手\n还要大。",
      "The little boy stands under a huge dinosaur skeleton in a museum, looking up, holding his own hand up beside one enormous toe bone.", 1),
    ]))

BOOKS.append(dict(
    slug="trex", seed=72000, title="霸王龙的牙齿", subtitle="一辈子换个不停",
    keyword="牙齿", style_label="平涂线条",
    style="children's picture book illustration, bold flat graphic art with thick clean outlines and "
          "flat fills, deep teal, rust orange and cream",
    character="wearing a rust orange t-shirt, dark teal shorts and white sneakers, short black hair",
    palette=P(("#22282b", "#5f7a7e", "#f2efe7", "#fcfaf5", "#c2542c", "#7a6a55", "#d6d2c6"),
              ("#e8e3d6", "#8fa5a8", "#101416", "#1b2124", "#d9714a", "#7a6a55", "#333a3d")),
    diagram=[2, 3, 4, 6, 8],
    pages=[
     ("玻璃柜里放着一颗牙。\n它比我的手掌还长，\n边上还有\n一排小锯齿。\n爸爸说那是霸王龙的。",
      "The little boy looks through a museum glass case at one huge dinosaur tooth on a stand, leaning close, curious.", 1),
     ("这颗牙有多大呢？\n和香蕉差不多长。\n露在牙床外面的\n只是上面一小截，\n底下还埋着一大半。",
      "A simple clear diagram, drawn flat and plain: one large pointed tooth shape and one banana shape lying side by side on a cream background, exactly the same length. Nothing else in the picture.", 0),
     ("牙的边上有锯齿，\n和面包刀一样。\n这样咬下去，\n不是切断，\n是撕开。",
      "A simple clear diagram, drawn flat and plain: one tooth edge shown large on a cream background with small even saw teeth along it, and one bread knife below it with the same saw edge. Nothing else in the picture.", 0),
     ("牙断了怎么办？\n不要紧。\n下面早就长好了新的，\n顶上来接着用，\n一辈子换个不停。",
      "A simple clear diagram, drawn flat and plain: one jaw cut open on a cream background showing one tooth standing in place and one new tooth growing underneath it, with an arrow pointing up. Nothing else in the picture.", 0),
     ("它咬得有多狠？\n一口下去，\n骨头都能咬碎。\n骨头碎了，\n里面的骨髓也吃得到。",
      "One large meat-eating dinosaur head biting down on a big bone on a cream background. Nothing else in the picture.", 0),
     ("我们咬东西的力气，\n和它一比\n差得太远了。\n它咬一口的力气，\n抵得上好几十个大人。",
      "A simple clear diagram, drawn flat and plain: two horizontal bars on a cream background starting from the same left edge, the top bar very short and the bottom bar running almost the whole width. Nothing else in the picture.", 0),
     ("它的头很大，\n头骨上却有好多空洞。\n这样又轻又结实，\n咬下去的时候\n才不会把自己震坏。",
      "One large dinosaur skull seen from the side on a cream background, with several big openings in the bone. Nothing else in the picture.", 0),
     ("它的前爪特别小，\n小到摸不到自己的嘴。\n可它力气不小，\n能牢牢钩住东西\n不让跑掉。",
      "A simple clear diagram, drawn flat and plain: one meat-eating dinosaur silhouette on a cream background with a circle drawn around its two very short front arms. Nothing else in the picture.", 0),
     ("它的鼻子很灵。\n风一吹过来，\n很远的地方\n有什么东西死掉了，\n它就闻得到。",
      "One meat-eating dinosaur standing with its head raised and nose lifted into the wind on a cream background. Nothing else in the picture.", 0),
     ("它吃活的，\n也吃死的。\n碰上现成的，\n就不用自己去追，\n省好多力气。",
      "One meat-eating dinosaur walking towards a big bone lying on the ground on a cream background. Nothing else in the picture.", 0),
     ("掉下来的牙\n埋进泥沙里，\n过了很久很久，\n慢慢变成石头。\n我们今天才捡得到。",
      "One large tooth lying half buried in layered ground on a cream background. Nothing else in the picture.", 0),
     ("我把手贴在玻璃上，\n和那颗牙比一比。\n它一颗牙，\n就有我半只手\n那么长。",
      "The little boy presses his open hand flat against the museum glass beside the big tooth, comparing them, smiling.", 1),
    ]))

BOOKS.append(dict(
    slug="longneck", seed=73000, title="长脖子够得到树顶", subtitle="脖子里有十五块骨头",
    keyword="蜥脚类", style_label="彩铅",
    style="children's picture book illustration, soft coloured pencil drawing with light hatching, "
          "forest green, warm brown and pale sky blue",
    character="wearing a pale blue t-shirt, brown shorts and white sneakers, short black hair",
    palette=P(("#2a2c24", "#6b7a5e", "#f1f2e9", "#fbfcf6", "#a8763e", "#77684f", "#d9dccb"),
              ("#e9ebdc", "#97a487", "#131610", "#1e2218", "#c59158", "#77684f", "#353a2c")),
    diagram=[2, 3, 5, 7, 9, 11],
    pages=[
     ("院子里的果子\n长得太高了。\n我踮起脚，\n伸直胳膊，\n还是够不到。",
      "The little boy stands under a fruit tree in a garden, up on his toes with one arm stretched high, still not reaching the fruit.", 1),
     ("有一种恐龙，\n脖子特别长。\n比一辆公交车还长，\n站在地上\n就能吃到三楼的叶子。",
      "A simple clear diagram, drawn flat and plain: one long-necked dinosaur silhouette on a cream background standing beside the outline of a three-storey building, its head level with the top floor. Nothing else in the picture.", 0),
     ("脖子这么长，\n里面有多少块骨头？\n十五块。\n我们的脖子里\n只有七块。",
      "A simple clear diagram, drawn flat and plain: two neck outlines side by side on a cream background, the long one divided into fifteen blocks and the short one into seven blocks. Nothing else in the picture.", 0),
     ("脖子长有个好处：\n不用走来走去。\n站在一个地方，\n脖子转一圈，\n周围的叶子都吃得到。",
      "One long-necked dinosaur standing still among several trees on a cream background, its head turned to one side reaching leaves. Nothing else in the picture.", 0),
     ("它的头却很小，\n和身体比起来\n小得不像话。\n头要是太重，\n脖子就抬不起来了。",
      "A simple clear diagram, drawn flat and plain: one long-necked dinosaur silhouette on a cream background with a circle drawn around its very small head. Nothing else in the picture.", 0),
     ("它的牙像一排耙子，\n只管把叶子捋下来，\n不嚼，\n直接吞下去。\n嚼太费时间了。",
      "One long-necked dinosaur head close up on a cream background pulling leaves off a branch with its rake-like teeth. Nothing else in the picture.", 0),
     ("不嚼怎么消化呢？\n它吞石头。\n石头在肚子里\n滚来滚去把叶子磨碎，\n代替牙齿干活。",
      "A simple clear diagram, drawn flat and plain: one stomach outline on a cream background with leaves and several round smooth stones inside it. Nothing else in the picture.", 0),
     ("它一天\n要吃好几百公斤叶子。\n吃完这一棵，\n就慢慢走到下一棵，\n一天到晚都在吃。",
      "One long-necked dinosaur walking slowly from one tree to another on a cream background. Nothing else in the picture.", 0),
     ("血要从心脏\n一直送到头上去，\n那么高。\n所以它的心脏\n特别大，特别有力气。",
      "A simple clear diagram, drawn flat and plain: one long-necked dinosaur body outline on a cream background with a heart marked in the chest and one arrow running all the way up the neck to the head. Nothing else in the picture.", 0),
     ("它的尾巴也很长，\n甩起来像一条鞭子。\n啪的一声，\n谁都不敢\n靠得太近。",
      "One long-necked dinosaur swinging its long tail on a cream background, motion lines behind the tail tip. Nothing else in the picture.", 0),
     ("脖子往前伸，\n尾巴往后伸，\n中间搭在四条腿上。\n整个身体\n就像一座桥，稳稳的。",
      "A simple clear diagram, drawn flat and plain: one long-necked dinosaur seen from the side on a cream background with its neck and tail drawn as the two arms of a bridge and its legs as the bridge supports. Nothing else in the picture.", 0),
     ("爸爸把我举起来，\n我一伸手\n就够到了那个果子。\n原来长脖子\n是这种感觉。",
      "The father lifts the little boy up on his shoulders in the garden and the boy reaches out and picks the fruit, delighted.", 1),
    ]))

BOOKS.append(dict(
    slug="triceratops", seed=74000, title="三角龙的角", subtitle="三只角和一块大盾",
    keyword="三角龙", style_label="蜡笔",
    style="children's picture book illustration, thick wax crayon drawing with grainy strokes, "
          "clay red, mustard yellow and dusty green",
    character="wearing a mustard yellow t-shirt, olive shorts and white sneakers, short black hair",
    palette=P(("#2e2620", "#7b6a58", "#f3efe6", "#fcfaf4", "#b0492f", "#8a7a5e", "#ded6c6"),
              ("#ebe4d7", "#a6937c", "#171109", "#231b12", "#cb6a4c", "#8a7a5e", "#3b3225")),
    diagram=[2, 3, 5, 7, 9, 11],
    pages=[
     ("这个头\n比我整个人还高。\n上面有三只角，\n后面还顶着\n一块大大的盾。",
      "The little boy stands beside a huge triceratops skull in a museum, looking up at it, his head no higher than the skull's beak.", 1),
     ("它的角一共三只。\n鼻子上一只短的，\n两只眼睛上面\n各有一只长的。\n所以它叫三角龙。",
      "A simple clear diagram, drawn flat and plain: one triceratops head seen from the front on a cream background with one short horn on the nose and one long horn above each eye, three horns in total. Nothing else in the picture.", 0),
     ("眼睛上面那两只角，\n有一米那么长，\n比大人的胳膊还长。\n尖尖的，\n谁也不敢乱碰。",
      "A simple clear diagram, drawn flat and plain: one long pointed horn shape lying beside one outstretched adult arm outline on a cream background, the horn clearly longer. Nothing else in the picture.", 0),
     ("脖子后面那块大盾，\n是骨头长出来的。\n它一低头，\n盾正好\n挡在脖子前面。",
      "One triceratops seen from the side on a cream background with its head lowered so the bony frill shields its neck. Nothing else in the picture.", 0),
     ("这块盾有什么用呢？\n能挡住咬过来的嘴，\n能撑得很大吓唬对手，\n同伴远远看见，\n也认得出是自己人。",
      "A simple clear diagram, drawn flat and plain: three small triceratops head shapes in a row on a cream background, the first with a bite mark stopped at the frill, the second with the frill drawn extra wide, the third with a patterned frill. Nothing else in the picture.", 0),
     ("两只三角龙\n也会打架。\n角对着角\n顶来顶去，\n谁先退开谁就算输。",
      "Two triceratops facing each other on a cream background with their horns locked together, pushing. Nothing else in the picture.", 0),
     ("它的嘴像鸟喙，\n又硬又尖，\n专门剪断粗树枝。\n后面的牙\n再把叶子磨碎。",
      "A simple clear diagram, drawn flat and plain: one triceratops jaw seen from the side on a cream background, the front drawn as a hard pointed beak and the back as rows of flat grinding teeth. Nothing else in the picture.", 0),
     ("它有四条腿，\n又粗又壮。\n身体那么重，\n走起路来\n地面都跟着抖。",
      "One triceratops walking on four thick sturdy legs on a cream background. Nothing else in the picture.", 0),
     ("它有多大呢？\n和一辆小汽车\n差不多长，\n可是要重得多，\n三辆车加起来才够。",
      "A simple clear diagram, drawn flat and plain: one triceratops silhouette and one car shape standing one above the other on a cream background, exactly the same length. Nothing else in the picture.", 0),
     ("它们常常\n一大群走在一起。\n小的走在中间，\n大的围在外面，\n角全都朝着外面。",
      "A group of triceratops standing in a ring on a cream background with the small ones in the middle and the big ones facing outward. Nothing else in the picture.", 0),
     ("它的头骨又大又硬，\n埋在泥沙里\n不容易碎。\n所以我们挖出来的\n三角龙头骨特别多。",
      "A simple clear diagram, drawn flat and plain: one cross-section of layered ground on a cream background with one large triceratops skull embedded in the middle layer. Nothing else in the picture.", 0),
     ("我摸了摸\n那块盾的边。\n凉凉的，硬硬的。\n它到底\n顶过多少次呢？",
      "The little boy reaches up and touches the edge of the triceratops skull's frill with one hand, thoughtful.", 1),
    ]))

BOOKS.append(dict(
    slug="dinoegg", seed=75000, title="恐龙蛋里面是什么", subtitle="壳太厚就出不来了",
    keyword="恐龙蛋", style_label="水彩",
    style="children's picture book illustration, soft transparent watercolour with clean wet washes, "
          "warm sand, pale peach and soft grey green",
    character="wearing a peach t-shirt, sand coloured shorts and white sneakers, short black hair",
    palette=P(("#33291f", "#7e7060", "#f5f1e8", "#fdfbf6", "#c77a4e", "#8f8266", "#e0d8c8"),
              ("#ece5d9", "#a99884", "#181207", "#241c12", "#d99368", "#8f8266", "#3c3427")),
    diagram=[2, 3, 5, 7, 11],
    pages=[
     ("柜子里放着几个蛋，\n灰灰的，\n看上去像石头。\n爸爸说，\n里面本来有小恐龙。",
      "The little boy leans close to a museum case holding several round fossil dinosaur eggs, looking at them, curious.", 1),
     ("恐龙蛋有多大呢？\n最大的\n和一个足球差不多。\n可再大的恐龙，\n蛋也大不到哪里去。",
      "A simple clear diagram, drawn flat and plain: one chicken egg shape and one football-sized egg shape side by side on a cream background, the big one clearly larger. Nothing else in the picture.", 0),
     ("蛋要是太大，\n壳就得很厚。\n壳太厚，\n里面的小恐龙\n就啄不破，出不来了。",
      "A simple clear diagram, drawn flat and plain: two eggs cut open side by side on a cream background, one with a thin shell and one with a very thick shell. Nothing else in the picture.", 0),
     ("下蛋以前，\n它先在地上挖一个坑，\n铺上叶子，\n再把蛋一个一个\n摆进去。",
      "One dinosaur crouching over a shallow nest pit lined with leaves on a cream background, placing eggs into it. Nothing else in the picture.", 0),
     ("蛋不是乱放的。\n有的绕成一圈一圈，\n中间空着。\n这样每一个蛋\n都晒得到太阳。",
      "A simple clear diagram, drawn flat and plain: one round nest seen from above on a cream background with eggs arranged in a ring around an empty middle. Nothing else in the picture.", 0),
     ("有的恐龙\n会趴在窝边上，\n用身体和前肢\n把蛋轻轻盖住，\n不让它们变凉。",
      "One feathered dinosaur sitting over a nest with its arms spread across the eggs on a cream background. Nothing else in the picture.", 0),
     ("蛋壳上有很多小孔，\n小到看不见。\n空气从小孔钻进去，\n里面的小恐龙\n才能呼吸。",
      "A simple clear diagram, drawn flat and plain: one piece of eggshell shown greatly magnified on a cream background with many tiny holes through it and small arrows passing inward. Nothing else in the picture.", 0),
     ("时候到了，\n小恐龙用鼻子上的小尖\n把壳顶开一道缝，\n再一点一点\n钻出来。",
      "One baby dinosaur pushing its head out through a crack in an egg on a cream background. Nothing else in the picture.", 0),
     ("刚出来的小恐龙\n很小，腿也软，\n站都站不稳。\n它们挤在一起，\n互相靠着取暖。",
      "Three newly hatched baby dinosaurs huddled together in a nest on a cream background. Nothing else in the picture.", 0),
     ("爸爸妈妈\n要一趟一趟\n把吃的带回来。\n窝里全是张着嘴\n等着吃的小家伙。",
      "One adult dinosaur standing over a nest of babies with their mouths open wide on a cream background. Nothing else in the picture.", 0),
     ("小恐龙长得很快。\n几年工夫，\n就从和猫一样大，\n长到比一辆车\n还要大。",
      "A simple clear diagram, drawn flat and plain: four dinosaur silhouettes in a row on a cream background, each much taller than the one before, with a rising line drawn over their heads. Nothing else in the picture.", 0),
     ("我趴在玻璃前面\n看那几个蛋。\n它们还是圆圆的，\n只是里面\n已经空了。",
      "The little boy rests his chin on the edge of the museum case, looking quietly at the round fossil eggs.", 1),
    ]))

BOOKS.append(dict(
    slug="fossil", seed=76000, title="化石是怎么来的", subtitle="骨头怎么变成石头",
    keyword="化石", style_label="矿物色粉",
    style="children's picture book illustration in mineral pigment style, layered earthy washes with "
          "fine dark outlines, ochre, slate grey and cream, textured and grainy",
    character="wearing a slate grey t-shirt, ochre shorts and white sneakers, short black hair",
    palette=P(("#2c241c", "#6f6153", "#f4efe6", "#fbf9f4", "#b5623a", "#8c7d69", "#dbd3c6"),
              ("#eae4d9", "#a49683", "#171008", "#221a10", "#c87a52", "#8c7d69", "#3a3125")),
    diagram=[2, 4, 5, 7, 9, 11],
    pages=[
     ("我在山边\n捡到一块石头，\n上面有一个\n弯弯的壳印。\n爸爸说，那是化石。",
      "The little boy squats on a hillside path holding a flat stone with a curved shell imprint on it, looking at it closely.", 1),
     ("很久以前，\n一只恐龙倒在河边。\n河水带来泥沙，\n一层一层\n把它盖住了。",
      "A simple clear diagram, drawn flat and plain: one dinosaur skeleton lying flat at the bottom of a cream background with several horizontal layers of sediment drawn stacked over it. Nothing else in the picture.", 0),
     ("软的地方\n先烂掉，不见了。\n只有骨头最硬，\n留在泥沙里，\n没有走。",
      "One dinosaur skeleton lying buried in the ground on a cream background, the bones clean and bare. Nothing else in the picture.", 0),
     ("泥沙越压越紧。\n水顺着缝\n渗进骨头里，\n水里带着矿物，\n一点一点把骨头换成石头。",
      "A simple clear diagram, drawn flat and plain: one bone cut open on a cream background with small arrows of water entering it and the inside slowly filling with stone speckles. Nothing else in the picture.", 0),
     ("这件事很慢很慢。\n慢到要过\n几千万年。\n那个时候，\n地球上还没有人。",
      "A simple clear diagram, drawn flat and plain: one very long horizontal bar on a cream background marked into equal sections, with a tiny mark at the far right end. Nothing else in the picture.", 0),
     ("后来地壳动了一下，\n埋在底下的那一层\n被顶了上来。\n风一吹，雨一冲，\n化石就露出来了。",
      "One hillside on a cream background with tilted rock layers and one bone showing at the surface. Nothing else in the picture.", 0),
     ("挖化石要很小心。\n先用刷子扫开沙，\n再用小凿子\n一点一点敲，\n急不得。",
      "A simple clear diagram, drawn flat and plain: three tools laid in a row on a cream background: one brush, one small chisel, one pick. Nothing else in the picture.", 0),
     ("挖出来以后，\n要用石膏\n把它整个包起来，\n像打石膏一样，\n免得路上碰碎了。",
      "One large fossil bone wrapped in a white plaster jacket on a cream background. Nothing else in the picture.", 0),
     ("运回来再一块一块拼。\n缺掉的地方，\n就照着别的骨头\n做一个补上去，\n颜色不一样。",
      "A simple clear diagram, drawn flat and plain: one dinosaur skeleton outline on a cream background with most bones drawn solid and three drawn with dashed outlines. Nothing else in the picture.", 0),
     ("化石会说话。\n牙齿告诉我们它吃什么，\n腿骨告诉我们它跑多快，\n蛋告诉我们\n它怎么带孩子。",
      "One tooth, one leg bone and one egg laid side by side on a cream background. Nothing else in the picture.", 0),
     ("不是每只恐龙\n都变得成化石。\n一万只里面，\n也许只有一只\n运气好，被泥沙埋住。",
      "A simple clear diagram, drawn flat and plain: many small identical dinosaur silhouettes arranged in a grid on a cream background, with exactly one of them filled in a strong colour. Nothing else in the picture.", 0),
     ("我把那块石头\n放进口袋。\n它在山里\n躺了那么久，\n今天被我捡到了。",
      "The little boy slips the flat shell-imprint stone into his pocket, standing on the hillside path, pleased.", 1),
    ]))

BOOKS.append(dict(
    slug="extinct", seed=77000, title="恐龙为什么不见了", subtitle="天上掉下来的那块石头",
    keyword="灭绝", style_label="油画棒",
    style="children's picture book illustration, bold oil pastel strokes with visible texture, "
          "deep indigo, ember orange and ash grey",
    character="wearing a deep indigo t-shirt, grey shorts and white sneakers, short black hair",
    palette=P(("#241f2b", "#66607a", "#f0eef2", "#fbfafc", "#c2582b", "#6f6656", "#d8d4dd"),
              ("#e8e5ee", "#948da8", "#12101a", "#1d1a26", "#d97a4c", "#6f6656", "#332f3f")),
    diagram=[2, 4, 6, 8, 10, 11],
    pages=[
     ("我问爸爸，\n恐龙去哪儿了？\n爸爸说，\n很久很久以前的一天，\n天上掉下来一块石头。",
      "The little boy sits on the floor beside his father with a toy dinosaur in his hand, looking up and asking a question.", 1),
     ("那块石头很大，\n有一座山那么大。\n它从天上直直砸下来，\n落在海边，\n砸出一个大坑。",
      "A simple clear diagram, drawn flat and plain: one round rock shape and one mountain outline side by side on a cream background, the same height. Nothing else in the picture.", 0),
     ("撞的那一下，\n地面抖了起来，\n海水推成一道大浪，\n附近的树\n全都倒了。",
      "One huge wave rolling over a shore with trees bending flat on a cream background. Nothing else in the picture.", 0),
     ("最要命的不是那一下。\n是撞起来的灰尘\n飘到天上，\n铺成厚厚一层，\n把太阳遮住了。",
      "A simple clear diagram, drawn flat and plain: one sun at the top of a cream background, one thick horizontal band of dust below it, and light arrows stopping at the band. Nothing else in the picture.", 0),
     ("太阳照不下来，\n地上就冷了。\n一冷就是好多年，\n连白天\n也是灰灰的。",
      "One cold grey landscape with bare ground under a dim sky on a cream background. Nothing else in the picture.", 0),
     ("没有太阳，\n植物就长不出来。\n植物死了，\n吃植物的恐龙\n跟着没饭吃。",
      "A simple clear diagram, drawn flat and plain: four shapes in a row on a cream background joined by arrows: a sun, a plant, a plant-eating dinosaur, a meat-eating dinosaur, with a cross drawn over the sun. Nothing else in the picture.", 0),
     ("个子大的最吃亏。\n它每天要吃那么多，\n现在一点也找不到，\n没过多久\n就撑不住了。",
      "One very large dinosaur standing alone on bare ground with its head lowered on a cream background. Nothing else in the picture.", 0),
     ("谁活下来了呢？\n个子小的，\n吃得少的，\n能钻进洞里的，\n能吃种子和虫子的。",
      "A simple clear diagram, drawn flat and plain: a cream background split into two columns, the left column holding three very large animal silhouettes each with a cross over it, the right column holding three small animal silhouettes with no cross. Nothing else in the picture.", 0),
     ("有一小支恐龙\n身上长着羽毛，\n个子小，会飞。\n它们活了下来，\n就是今天的鸟。",
      "One small feathered dinosaur flying up from a bare branch on a cream background. Nothing else in the picture.", 0),
     ("恐龙在地球上\n住了一亿六千万年。\n人住了多久呢？\n和它们比起来，\n还不到细细的一条线。",
      "A simple clear diagram, drawn flat and plain: one very long horizontal bar on a cream background and, beneath its right end, one extremely short bar starting from the same right edge. Nothing else in the picture.", 0),
     ("那一天\n在地里留下了记号。\n地层中间有一条灰线，\n线下面有恐龙，\n线上面，一只也没有了。",
      "A simple clear diagram, drawn flat and plain: one cross-section of stacked ground layers on a cream background with one thin dark line across the middle, three small dinosaur shapes embedded below the line and none above it. Nothing else in the picture.", 0),
     ("我看着窗外的麻雀。\n它跳了两下，\n飞走了。\n爸爸说，\n那也是恐龙。",
      "The little boy kneels on a chair at a window watching a sparrow on the sill outside, smiling.", 1),
    ]))

BOOKS.append(dict(
    slug="notdino", seed=78000, title="谁不是恐龙", subtitle="会飞的、游泳的，都不算",
    keyword="分类", style_label="钢笔淡彩",
    style="children's picture book illustration, fine pen and ink lines with light washes, "
          "muted olive, brick red and warm grey",
    character="wearing a brick red t-shirt, olive shorts and white sneakers, short black hair",
    palette=P(("#272621", "#6e6b5c", "#f2f1ea", "#fbfbf6", "#a8503a", "#847b64", "#dad7ca"),
              ("#e9e7db", "#9b9782", "#141309", "#1f1e14", "#c26a4f", "#847b64", "#373528")),
    diagram=[2, 3, 5, 7, 9, 11],
    pages=[
     ("我指着天上挂的那只说，\n这也是恐龙。\n爸爸摇摇头。\n它会飞，\n可它真的不是恐龙。",
      "The little boy in a museum points up at a large flying reptile model hanging from the ceiling, his father standing beside him.", 1),
     ("怎么分呢？\n看腿。\n恐龙的腿\n直直地长在身体下面，\n像四根柱子撑着。",
      "A simple clear diagram, drawn flat and plain: one animal body seen from the front on a cream background with its four legs running straight down underneath it like four posts. Nothing else in the picture.", 0),
     ("蜥蜴和鳄鱼不一样。\n它们的腿\n是朝两边撇出去的，\n走起路来\n身体左右扭。",
      "A simple clear diagram, drawn flat and plain: one animal body seen from the front on a cream background with its four legs bent out sideways away from the body. Nothing else in the picture.", 0),
     ("天上飞的那种叫翼龙。\n它的翅膀，\n是一根特别长的手指\n撑起来的一张皮。\n它不是恐龙。",
      "One flying reptile gliding with its wing membrane stretched from one very long finger, on a cream background. Nothing else in the picture.", 0),
     ("翅膀有三种做法。\n翼龙用一根手指撑，\n蝙蝠用四根手指撑，\n鸟用羽毛铺。\n各有各的办法。",
      "A simple clear diagram, drawn flat and plain: three wing outlines in a row on a cream background, the first with one very long finger bone, the second with four spread finger bones, the third with layered feathers. Nothing else in the picture.", 0),
     ("水里游的那些\n也不是恐龙。\n有的像一条大蜥蜴，\n有的长得像海豚，\n可它们都不算。",
      "Two large sea reptiles swimming underwater on a cream background, one long and lizard-like, one shaped like a dolphin. Nothing else in the picture.", 0),
     ("分成三堆就清楚了：\n天上飞的翼龙，\n水里游的大家伙，\n地上走的恐龙。\n只有最后一堆才叫恐龙。",
      "A simple clear diagram, drawn flat and plain: a cream background in three horizontal rows, the top row holding two flying shapes, the middle row two swimming shapes, the bottom row three walking shapes, with a ring drawn around the bottom row only. Nothing else in the picture.", 0),
     ("那时候的恐龙\n都在陆地上走。\n后来有一小支\n长出羽毛，飞了起来。\n那就是鸟。",
      "One small feathered dinosaur lifting off from the ground on a cream background. Nothing else in the picture.", 0),
     ("所以鸟\n反过来是恐龙。\n窗外的麻雀，\n院子里的鸡，\n都是恐龙的后代。",
      "A simple clear diagram, drawn flat and plain: one branching tree drawn on a cream background with a thick trunk marked by a dinosaur silhouette and one branch leading up to a bird silhouette. Nothing else in the picture.", 0),
     ("还有一个常弄混的。\n长毛的大象\n和剑齿虎，\n比恐龙晚得多，\n那时候恐龙早就没了。",
      "One woolly mammoth and one sabre-toothed cat standing on snowy ground on a cream background. Nothing else in the picture.", 0),
     ("把时间排一排\n就清楚了。\n先是恐龙，\n中间隔了好久好久，\n才轮到长毛象，最后是我们。",
      "A simple clear diagram, drawn flat and plain: one long horizontal timeline on a cream background with three marks placed far apart along it, a dinosaur shape at the first, a mammoth shape at the second and a small human shape at the third. Nothing else in the picture.", 0),
     ("我又看了一眼\n天上挂的那只。\n它不是恐龙。\n可它和恐龙，\n是一个时候的邻居。",
      "The little boy looks up once more at the hanging flying reptile model, thoughtful, one hand on the railing.", 1),
    ]))
