# -*- coding: utf-8 -*-
"""六本行为引导绘本：他和恐龙，讲怎么跟小朋友一起玩。

和第七批不同的地方：
  · 没有知识页，12 页全是他出镜的场景页；
  · 每本结尾都是同一个三步（停一停 / 说出来 / 给个办法），六本重复同一句，
    四岁的孩子靠重复记住，不靠道理；
  · 人物提示统一用「正常比例」那一版——写「只画头和肩」模型会把头画大。
"""
import json, os

SB = os.path.dirname(os.path.abspath(__file__))
BOY = ("A medium shot of the little boy seen from his knees up, {what}, "
       "his face turned towards the viewer, drawn with the natural body proportions of a real "
       "five-year-old child, his head in proportion to his body and about one fifth of his height, "
       "not a big-headed cartoon, his eyes calm and natural.")
PAL = {"ink": "#2a2419", "soft": "#7a6e5a", "ground": "#f3efe6", "paper": "#fdfbf6",
       "accent": "#b8552e", "bark": "#8a7f66", "line": "#ddd4c2", "ink_d": "#ece5d8",
       "soft_d": "#a99b83", "ground_d": "#16130e", "paper_d": "#211d16",
       "accent_d": "#e0805a", "bark_d": "#8a7f66", "line_d": "#37301f"}

BOOKS = [
 dict(slug="waitplay", title="我在搭东西，等一下", subtitle="不说「不行」，说「等一下」",
      seed=120000, style_label="彩色铅笔",
      style="children's picture book illustration, coloured pencil drawing with visible layered "
            "strokes and soft grain, warm mustard, leaf green and soft brown",
      character="wearing a mustard yellow t-shirt, green shorts and white sneakers, short black hair",
      pages=[
  ("我在地毯上搭恐龙乐园。\n一块，两块，三块。\n围栏快搭好了。",
   "kneeling on a living room carpet building a fence of wooden blocks around three toy dinosaurs"),
  ("表弟跑过来，\n蹲在我旁边。\n「我也要玩。」",
   "with a younger boy crouching down next to him on the carpet, both looking at the blocks"),
  ("我一下子把手挡住。\n「不行！」\n我怕他把围栏碰倒。",
   "putting one arm in front of his block fence, his mouth a small firm line, a younger boy beside him"),
  ("表弟走开了。\n我搭完了围栏，\n可是心里有点闷。",
   "sitting alone on the carpet beside the finished block fence, looking down, the room quiet"),
  ("爸爸坐下来问我：\n「你是不想他碰，\n还是不想他玩？」",
   "sitting on the carpet with his father, who sits beside him and looks at him while talking"),
  ("我说：我不想倒。\n爸爸说：那就告诉他\n「等一下」，不是「不行」。",
   "listening to his father, who holds up one finger, the blocks and toy dinosaurs in front of them"),
  ("我们先练一遍。\n爸爸当表弟，\n我说：「我在搭，等一下。」",
   "practising with his father on the carpet, his own hand raised with one finger up, saying a word"),
  ("第二天，表弟又来了。\n我停了一下，\n说：「我在搭，等一下好吗？」",
   "looking at the younger boy and holding up one finger, his other hand still on a block"),
  ("他等了一会儿。\n我搭好最后一块，\n说：「好了，你来。」",
   "placing the last block on the fence while the younger boy waits beside him, watching"),
  ("我给他两只恐龙，\n说：「你摆这边，\n我摆那边。」",
   "handing two toy dinosaurs to the younger boy, the block fence between them on the carpet"),
  ("我们一起摆了好久。\n围栏没有倒，\n乐园比刚才还大。",
   "sitting with the younger boy beside a big block enclosure full of toy dinosaurs, both smiling"),
  ("下次我也这样做：\n停一停，\n说出来，\n再给一个办法。",
   "sitting on the carpet holding one toy dinosaur, looking at the viewer, calm and pleased"),
      ]),
 dict(slug="askplay", title="我可以一起玩吗", subtitle="想加入的时候，这样开口",
      seed=121000, style_label="水彩",
      style="children's picture book illustration, soft watercolour with visible paper grain and "
            "gentle washes, sky blue, sand and warm grey",
      character="wearing a light blue t-shirt, grey shorts and white sneakers, short black hair",
      pages=[
  ("公园的沙坑里，\n两个小朋友在挖一条河。",
   "standing at the edge of a sandpit in a park watching two children dig a channel in the sand"),
  ("我很想一起挖，\n可是我站着不动。",
   "standing still at the edge of the sandpit, holding his own hands, watching the two children"),
  ("我小声说了一句，\n他们没听见。\n我更不敢说了。",
   "standing behind the two children in the sandpit, his mouth barely open, looking down"),
  ("妈妈蹲下来说：\n「他们不是不要你，\n是没听见。」",
   "crouching beside his mother at the edge of the sandpit, his mother speaking to him"),
  ("妈妈教我三句话。\n第一句：走近一点，\n看着他们。",
   "taking a step closer to the two children in the sandpit, looking straight at them"),
  ("第二句：大声一点。\n「我可以一起玩吗？」",
   "standing in the sandpit with the two children, his mouth open, one hand lifted a little"),
  ("第三句：说我能做什么。\n「我来搬沙子。」",
   "holding a small plastic bucket of sand and offering it to the two children in the sandpit"),
  ("一个小朋友说：\n「好啊，你挖这边。」",
   "kneeling in the sandpit beside one of the children, both digging the same channel"),
  ("有时候他们会说不。\n那不是我不好，\n是他们正玩到一半。",
   "sitting on the edge of the sandpit alone, calm, while the two children keep digging"),
  ("我可以等一等，\n或者先玩别的。\n等会儿再问一次。",
   "playing on his own with a small toy dinosaur on a low wall beside the sandpit"),
  ("后来河挖通了，\n水一下子流过去，\n我们三个都笑了。",
   "standing in the sandpit with the two children as water runs along the sand channel, all smiling"),
  ("想加入的时候：\n走近，\n问出来，\n说我能做什么。",
   "standing in the park holding a small bucket, looking at the viewer, cheerful and relaxed"),
      ]),
 dict(slug="taketurns", title="轮到谁了", subtitle="一个沙漏，两个人都不吵",
      seed=122000, style_label="蜡笔",
      style="children's picture book illustration, wax crayon drawing on textured paper with visible "
            "grainy strokes, warm orange, teal and cream",
      character="wearing an orange t-shirt, blue shorts and white sneakers, short black hair",
      pages=[
  ("家里只有一只大恐龙，\n今天来了两个小朋友。",
   "holding a large toy dinosaur while another child stands close by, both looking at the toy"),
  ("我们两个都拉着它。\n谁也不放手。",
   "holding one end of a large toy dinosaur while another child holds the other end, both pulling"),
  ("「是我先拿的！」\n「是我先看见的！」",
   "facing another child, both mouths open in a shout, the toy dinosaur between them"),
  ("妈妈没有把恐龙收走。\n她拿来一个小沙漏。",
   "watching his mother set a small sand timer on the low table in front of them"),
  ("「沙子漏完，就换人。」\n沙漏翻过来，\n沙子开始跑。",
   "watching the sand run down inside a small sand timer on the table, the other child beside him"),
  ("我先玩。\n我看着沙子，\n玩得很认真。",
   "playing with the toy dinosaur on the floor while the sand timer stands on the table nearby"),
  ("沙子漏完了。\n我把恐龙递过去，\n手有点舍不得。",
   "handing the toy dinosaur to the other child, his hand still half holding it"),
  ("轮到他了。\n我在旁边看，\n数他走了几步。",
   "sitting on the floor watching the other child walk the toy dinosaur along the carpet"),
  ("沙漏又翻过来。\n这回轮到我，\n我不用抢。",
   "taking the toy dinosaur back as the other child turns the sand timer over"),
  ("后来我们不用沙漏了。\n他说「给你」，\n我说「谢谢」。",
   "receiving the toy dinosaur from the other child, both children calm, the timer left on the table"),
  ("两个人一起玩，\n比一个人抢着玩\n好玩多了。",
   "kneeling on the floor with the other child, moving two toy dinosaurs together, both smiling"),
  ("轮到谁了？\n看沙漏。\n漏完就换人。",
   "holding the small sand timer up in front of him, looking at the viewer"),
      ]),
 dict(slug="loudvoice", title="霸王龙的大嗓门", subtitle="声音太大，朋友会跑开",
      seed=123000, style_label="厚涂水粉",
      style="children's picture book illustration, thick gouache with visible brush strokes and flat "
            "shapes, deep red, olive green and warm cream",
      character="wearing a red t-shirt, khaki shorts and white sneakers, short black hair",
      pages=[
  ("我最喜欢学霸王龙。\n「吼——！」\n声音好大。",
   "standing on a lawn with both hands raised like claws, his mouth wide open, shouting"),
  ("我一吼，\n旁边的小朋友\n往后退了一步。",
   "shouting with raised hands while another child takes a step back, hands over their own ears"),
  ("他们走开了。\n我一个人吼，\n没有人陪我。",
   "standing alone on the lawn with his hands down, looking at the empty grass"),
  ("爸爸说：\n「霸王龙很厉害，\n可是朋友的耳朵很软。」",
   "sitting on the grass with his father, who points gently at his own ear"),
  ("爸爸教我三个声音。\n小声：说悄悄话。",
   "leaning close to his father and whispering, one hand beside his mouth"),
  ("中声：一起玩的时候。\n「我们来玩恐龙。」",
   "talking normally to his father on the grass, both sitting, a toy dinosaur between them"),
  ("大声：在外面喊，\n或者有危险的时候。",
   "standing on the lawn calling out with both hands around his mouth, his father watching"),
  ("我试了一遍。\n爸爸说中声最好听。",
   "standing on the grass talking to his father, his hands relaxed at his sides"),
  ("第二天，我用中声说：\n「我们来玩恐龙好吗？」",
   "talking to another child on the lawn, holding a toy dinosaur out towards them"),
  ("他们没有跑开。\n有一个还问：\n「我当谁？」",
   "standing with two children on the lawn, all three holding toy dinosaurs"),
  ("我们一起当霸王龙，\n一起吼了一声。\n这回大家都在笑。",
   "standing with two children, all with hands raised like claws, mouths open, everyone laughing"),
  ("吼可以，\n先问一句：\n「我们一起吼好吗？」",
   "standing on the lawn with a toy dinosaur, looking at the viewer, smiling"),
      ]),
 dict(slug="sorryfix", title="我不是故意的", subtitle="弄坏了，可以补回来",
      seed=124000, style_label="钢笔淡彩",
      style="children's picture book illustration, fine ink line drawing with light watercolour "
            "washes, soft blue, warm grey and pale yellow",
      character="wearing a blue striped t-shirt, grey shorts and white sneakers, short black hair",
      pages=[
  ("小朋友搭了一座高塔，\n上面站着一只恐龙。",
   "looking at a tall tower of wooden blocks with a toy dinosaur on top, another child beside it"),
  ("我跑过去看，\n胳膊碰到了塔。\n哗啦——",
   "beside a toppling tower of wooden blocks, blocks scattering on the floor, his arm still out"),
  ("塔倒了。\n小朋友的眼睛红了。",
   "standing among scattered blocks while the other child sits on the floor looking upset"),
  ("我想说「不是我」，\n可是话卡在喉咙里。",
   "standing still with his mouth closed and his hands pressed together, looking at the floor"),
  ("我蹲下来，\n小声说：\n「对不起，我碰倒了。」",
   "crouching down beside the other child among the blocks, speaking quietly"),
  ("说完还不够。\n我问他：\n「我帮你搭回去，好吗？」",
   "holding one wooden block out towards the other child, both sitting among the fallen blocks"),
  ("他点了点头。\n我们一起捡积木。",
   "picking up wooden blocks from the floor together with the other child"),
  ("这回我们搭得宽一点，\n下面大，上面小。",
   "building a wide-based block tower on the floor with the other child, both concentrating"),
  ("恐龙又站上去了。\n这回没有倒。",
   "placing a toy dinosaur on top of a rebuilt block tower, the other child watching closely"),
  ("我以后走路会看着点，\n从旁边绕过去。",
   "walking carefully around the finished block tower, his arms close to his body"),
  ("他把恐龙递给我：\n「你也放一只吧。」",
   "receiving a toy dinosaur from the other child beside the rebuilt tower, both calm"),
  ("弄坏了不可怕：\n说对不起，\n再一起补回来。",
   "standing beside the block tower holding a toy dinosaur, looking at the viewer"),
      ]),
 dict(slug="aloneplay", title="我想自己玩一会儿", subtitle="说「不」也可以，好好说",
      seed=125000, style_label="水墨淡彩",
      style="children's picture book illustration, light ink wash painting with soft brush edges, "
            "muted green, warm grey and cream",
      character="wearing a green t-shirt, grey shorts and white sneakers, short black hair",
      pages=[
  ("有时候我不想说话，\n只想自己\n摆一排恐龙。",
   "sitting alone on the floor lining up small toy dinosaurs in a row, absorbed"),
  ("表弟又跑过来了。\n「一起玩！」",
   "sitting with his row of toy dinosaurs while a younger boy runs up beside him"),
  ("我不想。\n可是我怕他不高兴。",
   "sitting with his hand over one toy dinosaur, glancing sideways at the younger boy"),
  ("妈妈说：\n「不想玩可以说，\n说清楚就行。」",
   "sitting on the floor with his mother, who sits beside him and talks to him"),
  ("我想了想，说：\n「我想自己玩一会儿。」",
   "looking at the younger boy and speaking, one hand on his own chest"),
  ("再加一句时间：\n「摆完这一排就找你。」",
   "pointing at his row of toy dinosaurs while the younger boy listens beside him"),
  ("表弟去玩别的了。\n我把最后一只\n摆好了。",
   "placing the last toy dinosaur at the end of his long row on the floor"),
  ("我说到做到。\n我拿着两只恐龙\n去找他。",
   "walking across the room holding two toy dinosaurs, looking towards the younger boy"),
  ("「换我们一起玩了。」\n他一下子跳起来。",
   "handing one toy dinosaur to the younger boy, who jumps up happily"),
  ("要是他先说不呢？\n那我也等一等，\n不缠着他。",
   "sitting quietly on the floor with one toy dinosaur while the younger boy plays apart"),
  ("想自己玩不是不友好。\n说清楚，\n再说到做到。",
   "sitting on the floor with the younger boy, both moving toy dinosaurs, calm and friendly"),
  ("停一停，\n说出来，\n再给一个办法。\n三步，我记住了。",
   "standing holding one toy dinosaur, looking at the viewer, confident and calm"),
      ]),
]

for b in BOOKS:
    pages = [{"n": i, "zh": zh, "scene": BOY.format(what=what) + " Art style: " + b["style"] + ".",
              "has_boy": True}
             for i, (zh, what) in enumerate(b["pages"], 1)]
    assert len(pages) == 12, (b["slug"], len(pages))
    doc = {"workflow": "workflows/qwen_image_2512.json",
           "colophon": {"model": "Qwen-Image-Edit-2511 (Q3)", "lora": "照片参考，不用 LoRA",
                        "strength": 1.3},
           "title": b["title"], "subtitle": b["subtitle"], "slug": b["slug"],
           "seed_base": b["seed"], "character": b["character"], "style": b["style"],
           "style_label": b["style_label"], "keyword": "", "diagram_pages": [],
           "palette": PAL, "neg_extra": "", "pages": pages}
    p = os.path.join(SB, "story_" + b["slug"] + ".json")
    json.dump(doc, open(p, "w", encoding="utf-8", newline="\n"), ensure_ascii=False, indent=2)
    print(b["slug"], b["title"], len(pages), "页")
