[general]
caption_extension = ".txt"
shuffle_caption = false

[[datasets]]
resolution = 512
batch_size = 1
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 256
max_bucket_reso = 1024

  [[datasets.subsets]]
  image_dir = "C:/FlowDev/githubdevitems/comfyUIItems/lora_training/dataset"
  num_repeats = 1
